# Generated by Django 5.2.12 on 2026-03-27 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_os_demarrage', models.DateField(blank=True, null=True, verbose_name="Date de l'OS de démarrage")),
                ('duree_contractuelle_jours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée contractuelle (jours ouvrés)')),
                ('date_fin_contractuelle', models.DateField(blank=True, null=True, verbose_name='Date de fin contractuelle')),
                ('montant_marche_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant initial du marché HT (€)')),
                ('montant_travaux_supplementaires_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Travaux supplémentaires / avenants HT (€)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suivis_en_tant_qu_entreprise', to='organisations.organisation', verbose_name='Entreprise principale')),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_execution', to='projets.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': "Suivi d'exécution",
                'verbose_name_plural': "Suivis d'exécution",
                'db_table': 'execution_suivi',
            },
        ),
        migrations.CreateModel(
            name='OrdreService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Numéro')),
                ('type_ordre', models.CharField(choices=[('demarrage', 'Ordre de démarrage'), ('suspension', 'Ordre de suspension'), ('reprise', 'Ordre de reprise'), ('modification', 'Ordre de modification'), ('arret_definitif', 'Arrêt définitif')], max_length=20, verbose_name='Type')),
                ('date_emission', models.DateField(verbose_name="Date d'émission")),
                ('objet', models.CharField(max_length=500, verbose_name='Objet')),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu')),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_service', to='execution.suiviexecution', verbose_name='Suivi')),
            ],
            options={
                'verbose_name': 'Ordre de service',
                'verbose_name_plural': 'Ordres de service',
                'db_table': 'execution_ordre_service',
                'ordering': ['suivi', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='SituationTravaux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Numéro de situation')),
                ('periode_debut', models.DateField(verbose_name='Début de période')),
                ('periode_fin', models.DateField(verbose_name='Fin de période')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours de rédaction'), ('soumise', "Soumise à l'entreprise"), ('acceptee', 'Acceptée'), ('contestee', 'Contestée'), ('validee_moa', 'Validée par la MOA'), ('payee', 'Payée')], default='en_cours', max_length=20)),
                ('montant_cumule_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant cumulé HT (€)')),
                ('montant_periode_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant de la période HT (€)')),
                ('avancement_financier_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Avancement financier (%)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='execution.suiviexecution', verbose_name='Suivi')),
            ],
            options={
                'verbose_name': 'Situation de travaux',
                'verbose_name_plural': 'Situations de travaux',
                'db_table': 'execution_situation',
                'ordering': ['suivi', 'numero'],
                'unique_together': {('suivi', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='CompteRenduChantier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Numéro de réunion')),
                ('date_reunion', models.DateField(verbose_name='Date de la réunion')),
                ('ordre_du_jour', models.TextField(blank=True, verbose_name='Ordre du jour')),
                ('contenu', models.TextField(verbose_name='Contenu de la réunion')),
                ('decisions', models.TextField(blank=True, verbose_name='Décisions et points à traiter')),
                ('avancement_physique_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Avancement physique (%)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_diffusion', models.DateTimeField(blank=True, null=True)),
                ('redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comptes_rendus_rediges', to=settings.AUTH_USER_MODEL, verbose_name='Rédacteur')),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_rendus', to='execution.suiviexecution', verbose_name='Suivi')),
            ],
            options={
                'verbose_name': 'Compte rendu de chantier',
                'verbose_name_plural': 'Comptes rendus de chantier',
                'db_table': 'execution_compte_rendu',
                'ordering': ['suivi', '-date_reunion'],
                'unique_together': {('suivi', 'numero')},
            },
        ),
    ]
