# Generated by Django on 2026-04-01

from django.db import migrations, models

import applications.execution.models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suiviexecution",
            name="observations_pilotage",
            field=models.TextField(blank=True, verbose_name="Observations de pilotage"),
        ),
        migrations.AddField(
            model_name="suiviexecution",
            name="points_vigilance",
            field=models.JSONField(blank=True, default=list, verbose_name="Points de vigilance"),
        ),
        migrations.AddField(
            model_name="suiviexecution",
            name="processus_maitrise",
            field=models.JSONField(
                blank=True,
                default=applications.execution.models.obtenir_processus_execution_par_defaut,
                verbose_name="Processus maîtrisés",
            ),
        ),
        migrations.AddField(
            model_name="suiviexecution",
            name="prochaines_actions",
            field=models.JSONField(blank=True, default=list, verbose_name="Prochaines actions"),
        ),
    ]
