# Generated by Django 5.2 on 2026-04-02 12:06

import applications.execution.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_planning_calendrier_ressources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningchantier',
            name='jours_ouvres',
            field=models.JSONField(blank=True, default=applications.execution.models.obtenir_jours_ouvres_par_defaut, verbose_name='Jours ouvrés actifs'),
        ),
    ]
