# Generated by Django 5.2.12 on 2026-03-27 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroitFin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Code du droit')),
                ('module', models.CharField(max_length=100, verbose_name='Module')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('libelle', models.CharField(max_length=200)),
                ('accorde', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Droit fin',
                'verbose_name_plural': 'Droits fins',
                'db_table': 'comptes_droit_fin',
            },
        ),
        migrations.CreateModel(
            name='JournalConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courriel_saisi', models.EmailField(max_length=254)),
                ('date_tentative', models.DateTimeField(auto_now_add=True)),
                ('succes', models.BooleanField()),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agent_navigateur', models.TextField(blank=True)),
                ('motif_echec', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Journal de connexion',
                'verbose_name_plural': 'Journaux de connexion',
                'db_table': 'comptes_journal_connexion',
                'ordering': ['-date_tentative'],
            },
        ),
        migrations.CreateModel(
            name='ProfilDroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SUPER_ADMIN', 'Administrateur système'), ('ADMIN_BUREAU', 'Administrateur du bureau'), ('DIRECTEUR_TECH', 'Directeur technique'), ('ECONOMISTE_SR', 'Économiste senior'), ('ECONOMISTE_JR', 'Économiste junior'), ('CHARGE_AFFAIRES', "Chargé d'affaires"), ('CONDUCTEUR_TRAVAUX', 'Conducteur de travaux'), ('REDACTEUR_TECH', 'Rédacteur technique'), ('CLIENT', "Client / Maître d'ouvrage"), ('PARTENAIRE', 'Partenaire / Co-traitant'), ('SOUS_TRAITANT', 'Sous-traitant'), ('LECTURE_SEULE', 'Visiteur — lecture seule')], max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Profil de droits',
                'verbose_name_plural': 'Profils de droits',
                'db_table': 'comptes_profil_droit',
                'ordering': ['ordre_affichage', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('courriel', models.EmailField(max_length=254, unique=True, verbose_name='Adresse de courriel')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('fonction', models.CharField(blank=True, max_length=200, verbose_name='Fonction')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('est_staff', models.BooleanField(default=False)),
                ('est_super_admin', models.BooleanField(default=False, verbose_name='Super-administrateur')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('derniere_connexion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('tentatives_connexion', models.PositiveSmallIntegerField(default=0)),
                ('verrouille_jusqu_au', models.DateTimeField(blank=True, null=True)),
                ('langue', models.CharField(default='fr', max_length=5, verbose_name='Langue')),
                ('fuseau_horaire', models.CharField(default='Europe/Paris', max_length=50)),
                ('notifications_courriel', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'comptes_utilisateur',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
