# Generated by Django on 2026-04-02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="courriel_verifie_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="invitation_envoyee_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="JetonReinitialisationMotDePasse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("courriel", models.EmailField(max_length=254)),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("expire_le", models.DateTimeField()),
                ("utilise_le", models.DateTimeField(blank=True, null=True)),
                ("message_id", models.CharField(blank=True, max_length=255)),
                ("utilisateur", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jetons_reinitialisation", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Jeton de réinitialisation",
                "verbose_name_plural": "Jetons de réinitialisation",
                "db_table": "comptes_jeton_reinitialisation",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="InvitationUtilisateur",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("courriel", models.EmailField(max_length=254)),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("expire_le", models.DateTimeField()),
                ("utilise_le", models.DateTimeField(blank=True, null=True)),
                ("message_id", models.CharField(blank=True, max_length=255)),
                ("cree_par", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invitations_emises", to=settings.AUTH_USER_MODEL)),
                ("utilisateur", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Invitation utilisateur",
                "verbose_name_plural": "Invitations utilisateurs",
                "db_table": "comptes_invitation_utilisateur",
                "ordering": ["-date_creation"],
            },
        ),
    ]
