# Generated by Django 5.2.12 on 2026-03-27 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('courriel', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('sujet', models.CharField(choices=[('devis', 'Demande de devis'), ('information', "Demande d'information"), ('partenariat', 'Partenariat'), ('recrutement', 'Candidature'), ('autre', 'Autre')], default='information', max_length=20)),
                ('message', models.TextField()),
                ('traitee', models.BooleanField(default=False)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'db_table': 'site_public_contact',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description_courte', models.CharField(blank=True, max_length=400)),
                ('description_longue', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=100)),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=100)),
                ('est_publie', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
                'db_table': 'site_public_prestation',
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('fonction', models.CharField(blank=True, max_length=200)),
                ('biographie', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='site_public/equipe/')),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=100)),
                ('est_publie', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_vitrine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'db_table': 'site_public_membre',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('annee', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('montant_travaux_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant travaux HT (€)')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='site_public/realisations/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('est_publie', models.BooleanField(default=False)),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=100)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('projet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realisation_vitrine', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'db_table': 'site_public_realisation',
                'ordering': ['-annee', 'ordre_affichage'],
            },
        ),
    ]
