# Generated by Django 5.2 on 2026-03-31 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_public', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeDemarche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10, verbose_name='Numéro affiché (ex : 01, 02)')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=100)),
                ('est_publiee', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Étape de la démarche',
                'verbose_name_plural': 'Étapes de la démarche',
                'db_table': 'site_public_etape_demarche',
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.CharField(max_length=50, verbose_name='Valeur (ex : 15, 100%)')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='Unité (optionnel)')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé descriptif')),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=100)),
                ('est_publie', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chiffre clé',
                'verbose_name_plural': 'Chiffres clés',
                'db_table': 'site_public_statistique',
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='ValeurSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône lucide-react (ex : Shield, BarChart3).", max_length=100)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=100)),
                ('est_publiee', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Valeur / avantage',
                'verbose_name_plural': 'Valeurs / avantages',
                'db_table': 'site_public_valeur',
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.AddField(
            model_name='prestation',
            name='couleur',
            field=models.CharField(choices=[('primaire', 'Bleu primaire'), ('amber', 'Ambre'), ('green', 'Vert'), ('indigo', 'Indigo'), ('purple', 'Violet'), ('rose', 'Rose'), ('slate', 'Ardoise'), ('orange', 'Orange')], default='primaire', max_length=20, verbose_name='Couleur de la carte'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='points_forts',
            field=models.JSONField(blank=True, default=list, help_text='Liste JSON de textes courts (ex : ["Devis détaillés", "Traçabilité"]).', verbose_name='Points forts'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='icone',
            field=models.CharField(blank=True, help_text="Nom de l'icône lucide-react (ex : TrendingUp, Hammer).", max_length=100),
        ),
        migrations.CreateModel(
            name='ConfigurationRGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeau_actif', models.BooleanField(default=True, verbose_name='Bandeau de consentement actif')),
                ('texte_bandeau', models.TextField(blank=True, default="Nous utilisons des cookies strictement nécessaires au fonctionnement de la plateforme. Aucun cookie de traçage ou publicitaire n'est utilisé.", verbose_name='Texte du bandeau')),
                ('texte_bouton_accepter', models.CharField(default='Accepter', max_length=100, verbose_name='Texte bouton Accepter')),
                ('texte_bouton_refuser', models.CharField(default='Refuser', max_length=100, verbose_name='Texte bouton Refuser')),
                ('texte_bouton_personnaliser', models.CharField(default='Personnaliser', max_length=100, verbose_name='Texte bouton Personnaliser')),
                ('afficher_bouton_personnaliser', models.BooleanField(default=False, verbose_name='Afficher le bouton Personnaliser')),
                ('duree_consentement_jours', models.PositiveIntegerField(default=365, verbose_name='Durée de validité du consentement (jours)')),
                ('cookies_necessaires_description', models.TextField(blank=True, default='Cookies indispensables au fonctionnement du site (session, sécurité).', verbose_name='Description cookies nécessaires')),
                ('cookies_analytiques_actifs', models.BooleanField(default=False, verbose_name='Activer les cookies analytiques')),
                ('cookies_analytiques_description', models.TextField(blank=True, default="Cookies permettant d'analyser l'audience du site de manière anonyme.", verbose_name='Description cookies analytiques')),
                ('cookies_marketing_actifs', models.BooleanField(default=False, verbose_name='Activer les cookies marketing')),
                ('cookies_marketing_description', models.TextField(blank=True, default='Cookies permettant de personnaliser les publicités.', verbose_name='Description cookies marketing')),
                ('lien_politique_confidentialite', models.CharField(default='/politique-de-confidentialite', max_length=200, verbose_name='Lien vers la politique de confidentialité')),
                ('lien_gestion_cookies', models.CharField(default='/gestion-des-cookies', max_length=200, verbose_name='Lien vers la page de gestion des cookies')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations_rgpd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration RGPD',
                'verbose_name_plural': 'Configuration RGPD',
                'db_table': 'site_public_configuration_rgpd',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_bureau', models.CharField(default='BEE', max_length=200, verbose_name="Nom du bureau d'études")),
                ('slogan', models.CharField(blank=True, max_length=500, verbose_name='Slogan')),
                ('description_courte', models.TextField(blank=True, verbose_name='Description courte')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_public/logo/', verbose_name='Logo')),
                ('logo_pied_de_page', models.ImageField(blank=True, null=True, upload_to='site_public/logo/', verbose_name='Logo pied de page (optionnel — utilise logo principal si absent)')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_public/favicon/', verbose_name='Favicon')),
                ('titre_hero', models.CharField(default="L'expertise économique au service de vos projets de construction", max_length=300, verbose_name='Titre du héros')),
                ('sous_titre_hero', models.TextField(blank=True, default="Économie, dimensionnement voirie, métrés, pièces écrites, appels d'offres et suivi d'exécution — une plateforme intégrée pour des études rigoureuses et traçables.", verbose_name='Sous-titre du héros')),
                ('texte_cta_principal', models.CharField(default='Nos prestations', max_length=100, verbose_name='Texte du bouton principal')),
                ('texte_cta_secondaire', models.CharField(default='Nous contacter', max_length=100, verbose_name='Texte du bouton secondaire')),
                ('etiquette_hero', models.CharField(blank=True, default="Bureau d'études spécialisé BTP · VRD · Économie de la construction", max_length=200, verbose_name='Étiquette héros (bandeau discret au-dessus du titre)')),
                ('courriel_contact', models.EmailField(blank=True, max_length=254, verbose_name='Courriel de contact')),
                ('telephone_contact', models.CharField(blank=True, max_length=30, verbose_name='Téléphone de contact')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('afficher_stats', models.BooleanField(default=True, verbose_name='Afficher les chiffres clés')),
                ('afficher_valeurs', models.BooleanField(default=True, verbose_name='Afficher les valeurs / avantages')),
                ('afficher_demarche', models.BooleanField(default=True, verbose_name='Afficher la section démarche')),
                ('afficher_realisations', models.BooleanField(default=False, verbose_name='Afficher les réalisations')),
                ('afficher_equipe', models.BooleanField(default=False, verbose_name='Afficher la section équipe')),
                ('afficher_contact', models.BooleanField(default=True, verbose_name='Afficher le formulaire de contact')),
                ('texte_cta_bandeau', models.CharField(blank=True, default='Vous avez un projet de construction ?', max_length=300, verbose_name='Titre du bandeau CTA')),
                ('texte_description_bandeau', models.TextField(blank=True, verbose_name='Texte descriptif du bandeau CTA')),
                ('meta_titre', models.CharField(blank=True, max_length=300, verbose_name='Meta titre (balise <title>)')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='Meta description')),
                ('mots_cles', models.CharField(blank=True, max_length=500, verbose_name='Mots-clés SEO')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations_site', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
                'db_table': 'site_public_configuration',
            },
        ),
        migrations.CreateModel(
            name='PageStatique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text='Identifiant URL (ex : politique-de-confidentialite).', max_length=80, unique=True)),
                ('type_page', models.CharField(choices=[('politique_confidentialite', 'Politique de confidentialité'), ('mentions_legales', 'Mentions légales'), ('cgu', "Conditions générales d'utilisation"), ('gestion_cookies', 'Gestion des cookies'), ('autre', 'Autre')], default='autre', max_length=40)),
                ('titre', models.CharField(max_length=300)),
                ('contenu', models.TextField(help_text='Contenu en HTML ou Markdown. Affiché tel quel côté client.')),
                ('est_publiee', models.BooleanField(default=True, verbose_name='Publiée')),
                ('afficher_dans_pied_de_page', models.BooleanField(default=True, verbose_name='Lien dans le pied de page')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_statiques_modifiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page statique',
                'verbose_name_plural': 'Pages statiques',
                'db_table': 'site_public_page_statique',
                'ordering': ['titre'],
            },
        ),
    ]
