# Generated by Django 5.2 on 2026-04-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_public', '0005_supprimer_textes_par_defaut_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsite',
            name='contenu_accueil',
            field=models.JSONField(blank=True, default=dict, help_text="Contient les textes et blocs éditoriaux de la page d'accueil : sections, labels, indicateurs, secteurs et méthodes.", verbose_name="Contenu éditorial de la page d'accueil"),
        ),
        migrations.AddField(
            model_name='configurationsite',
            name='sigle',
            field=models.CharField(blank=True, default='', help_text="Utilisé si aucun logo n'est chargé.", max_length=12, verbose_name='Sigle de remplacement'),
        ),
    ]
