# Generated by Django 5.2 on 2026-04-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_public", "0006_configurationsite_contenu_accueil_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationsite",
            name="contenus_pages",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Contient les textes structurés des pages publiques : contact, méthode, prestations et références.",
                verbose_name="Contenus éditoriaux des pages publiques",
            ),
        ),
    ]
