# Generated by Django on 2026-04-02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalCourriel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("origine", models.CharField(choices=[("plateforme", "Plateforme"), ("notification", "Notification"), ("invitation", "Invitation"), ("reinitialisation", "Réinitialisation"), ("contact", "Contact"), ("webmail", "Webmail")], default="plateforme", max_length=32)),
                ("statut", models.CharField(choices=[("succes", "Succès"), ("echec", "Échec")], max_length=16)),
                ("sujet", models.CharField(max_length=255)),
                ("expediteur", models.EmailField(max_length=254)),
                ("destinataires", models.JSONField(blank=True, default=list)),
                ("copie", models.JSONField(blank=True, default=list)),
                ("copie_cachee", models.JSONField(blank=True, default=list)),
                ("message_id", models.CharField(blank=True, max_length=255)),
                ("erreur", models.TextField(blank=True)),
                ("contexte", models.JSONField(blank=True, default=dict)),
                ("nombre_pieces_jointes", models.PositiveSmallIntegerField(default=0)),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                ("utilisateur", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="journaux_courriels", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Journal de courriel",
                "verbose_name_plural": "Journal des courriels",
                "db_table": "messagerie_journal_courriel",
                "ordering": ["-date_envoi"],
            },
        ),
    ]
