# Generated by Django 5.2.12 on 2026-03-27 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=100, verbose_name='Icône')),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de documents',
                'db_table': 'documents_type',
                'ordering': ['ordre_affichage', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, verbose_name='Référence document')),
                ('intitule', models.CharField(max_length=500, verbose_name='Intitulé')),
                ('version', models.CharField(default='A', max_length=20, verbose_name='Indice / version')),
                ('est_version_courante', models.BooleanField(default=True, verbose_name='Version courante')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('nom_fichier_origine', models.CharField(blank=True, max_length=255)),
                ('taille_octets', models.PositiveBigIntegerField(blank=True, null=True)),
                ('type_mime', models.CharField(blank=True, max_length=100)),
                ('empreinte_sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_revision', 'En révision'), ('en_validation', 'En validation'), ('valide', 'Validé'), ('diffuse', 'Diffusé'), ('obsolete', 'Obsolète'), ('archive', 'Archivé')], default='brouillon', max_length=30, verbose_name='Statut')),
                ('origine', models.CharField(choices=[('interne', 'Produit en interne'), ('recu', "Reçu de l'extérieur"), ('ocr', 'Numérisé via OCR'), ('genere', 'Généré automatiquement')], default='interne', max_length=20, verbose_name='Origine')),
                ('ocr_effectue', models.BooleanField(default=False, verbose_name='OCR effectué')),
                ('contenu_texte', models.TextField(blank=True, verbose_name='Contenu extrait (OCR)')),
                ('mots_cles', models.JSONField(blank=True, default=list, verbose_name='Mots-clés extraits')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('acces_client', models.BooleanField(default=False, verbose_name='Accessible au client')),
                ('acces_partenaire', models.BooleanField(default=False, verbose_name='Accessible au partenaire')),
                ('confidentiel', models.BooleanField(default=False, verbose_name='Confidentiel')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_crees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('document_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.document', verbose_name='Version précédente')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projets.lot', verbose_name='Lot')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projets.projet', verbose_name='Projet')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.typedocument', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents_document',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='DiffusionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire_contact', models.CharField(blank=True, max_length=200)),
                ('mode_diffusion', models.CharField(choices=[('courriel', 'Courriel'), ('courrier', 'Courrier postal'), ('plateforme', 'Plateforme en ligne'), ('main_propre', 'Remise en main propre')], default='courriel', max_length=50)),
                ('date_diffusion', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation', verbose_name='Destinataire')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffusions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Diffusion',
                'verbose_name_plural': 'Diffusions',
                'db_table': 'documents_diffusion',
                'ordering': ['-date_diffusion'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField(verbose_name="Contenu de l'annotation")),
                ('page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Page')),
                ('resolue', models.BooleanField(default=False, verbose_name='Résolue')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='documents.document')),
            ],
            options={
                'verbose_name': 'Annotation',
                'verbose_name_plural': 'Annotations',
                'db_table': 'documents_annotation',
                'ordering': ['document', 'date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['projet', 'statut'], name='documents_d_projet__4c66e0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['reference'], name='documents_d_referen_a458fb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type_document'], name='documents_d_type_do_374a7d_idx'),
        ),
    ]
