# Generated by Django 5.2 on 2026-04-03 21:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_reparer_versions_courantes'),
        ('projets', '0004_projet_qualification_wizard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierDocumentProjet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, verbose_name='Code')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=100)),
                ('est_systeme', models.BooleanField(default=False, verbose_name='Dossier système')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='documents.dossierdocumentprojet', verbose_name='Dossier parent')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_documents', to='projets.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Dossier documentaire projet',
                'verbose_name_plural': 'Dossiers documentaires projet',
                'db_table': 'documents_dossier_projet',
                'ordering': ['ordre', 'intitule'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.dossierdocumentprojet', verbose_name='Dossier GED'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['projet', 'dossier'], name='documents_d_projet__4790eb_idx'),
        ),
        migrations.AddIndex(
            model_name='dossierdocumentprojet',
            index=models.Index(fields=['projet', 'ordre'], name='documents_d_projet__90779c_idx'),
        ),
        migrations.AddIndex(
            model_name='dossierdocumentprojet',
            index=models.Index(fields=['projet', 'code'], name='documents_d_projet__1375b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dossierdocumentprojet',
            unique_together={('projet', 'parent', 'code')},
        ),
    ]
