# Generated by Django 5.2.12 on 2026-03-27 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudeVoirie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=300, verbose_name="Intitulé de l'étude")),
                ('type_voie', models.CharField(choices=[('voie_urbaine', 'Voie urbaine'), ('route_departementale', 'Route départementale'), ('voie_communale', 'Voie communale'), ('parking', 'Parking / aire de stationnement'), ('voie_industrielle', 'Voie industrielle / desserte'), ('piste_cyclable', 'Piste cyclable'), ('trottoir', 'Trottoir / cheminement piéton')], default='voie_urbaine', max_length=30, verbose_name='Type de voie')),
                ('tmja_vl', models.PositiveIntegerField(default=0, verbose_name='TMJA — véhicules légers (VL/j)')),
                ('tmja_pl', models.PositiveIntegerField(default=0, verbose_name='TMJA — poids lourds (PL/j)')),
                ('duree_vie_ans', models.PositiveSmallIntegerField(blank=True, help_text='Laisser vide pour utiliser le paramètre système.', null=True, verbose_name='Durée de vie cible (ans)')),
                ('taux_croissance_annuel', models.DecimalField(blank=True, decimal_places=4, help_text='Ex : 0.02 pour 2 %. Laisser vide pour utiliser le paramètre système.', max_digits=5, null=True, verbose_name='Taux de croissance annuel du trafic')),
                ('cbr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Indice CBR mesuré')),
                ('classe_plateforme', models.CharField(blank=True, choices=[('PF1', 'PF1'), ('PF2', 'PF2'), ('PF3', 'PF3'), ('PF4', 'PF4')], help_text='Si CBR non disponible.', max_length=5, verbose_name='Classe de plate-forme')),
                ('zone_climatique', models.CharField(choices=[('temperee', 'Tempérée'), ('montagneuse', 'Montagneuse'), ('oceanique', 'Océanique')], default='temperee', max_length=20, verbose_name='Zone climatique')),
                ('proximite_eau', models.BooleanField(default=False, verbose_name='Zone humide / proximité eau')),
                ('epaisseur_totale_max_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Épaisseur totale maximale (cm)')),
                ('type_structure_prefere', models.CharField(blank=True, choices=[('SOUPLE', 'Structure souple'), ('SEMI_RIGIDE', 'Structure semi-rigide'), ('GB', 'Grave-bitume'), ('BC', 'Béton de ciment')], max_length=20, verbose_name='Type de structure préféré')),
                ('resultats_calcul', models.JSONField(blank=True, help_text='Résultat JSON complet retourné par le moteur de calcul.', null=True, verbose_name='Résultats du dimensionnement')),
                ('date_calcul', models.DateTimeField(blank=True, null=True, verbose_name='Date du dernier calcul')),
                ('calcul_conforme', models.BooleanField(blank=True, null=True, verbose_name='Résultat conforme')),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etudes_voirie_creees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projets.lot', verbose_name='Lot')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudes_voirie', to='projets.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Étude de voirie',
                'verbose_name_plural': 'Études de voirie',
                'db_table': 'voirie_etude',
                'ordering': ['-date_modification'],
            },
        ),
    ]
