# Generated by Django 5.2.12 on 2026-03-27 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé')),
                ('type_procedure', models.CharField(choices=[('appel_offres_ouvert', "Appel d'offres ouvert"), ('appel_offres_restreint', "Appel d'offres restreint"), ('procedure_adaptee', 'Procédure adaptée (MAPA)'), ('procedure_negociee', 'Procédure négociée'), ('marche_gre_a_gre', 'Marché de gré à gré'), ('concours', 'Concours')], max_length=30, verbose_name='Type de procédure')),
                ('statut', models.CharField(choices=[('preparation', 'Préparation du DCE'), ('publie', 'Publié'), ('questions_reponses', 'Questions / réponses'), ('clos', 'Clos'), ('depouille', 'Dépouillé'), ('attribue', 'Attribué'), ('infructueux', 'Infructueux'), ('abandonne', 'Abandonné')], default='preparation', max_length=20, verbose_name='Statut')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('date_limite_questions', models.DateField(blank=True, null=True, verbose_name='Date limite des questions')),
                ('date_limite_remise', models.DateTimeField(blank=True, null=True, verbose_name='Date limite de remise')),
                ('date_ouverture_plis', models.DateTimeField(blank=True, null=True, verbose_name="Date d'ouverture des plis")),
                ('date_attribution', models.DateField(blank=True, null=True, verbose_name="Date d'attribution prévue")),
                ('montant_estime_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant estimé HT (€)')),
                ('criteres_jugement', models.JSONField(blank=True, default=list, help_text='[{libelle, ponderation_pct, description}]', verbose_name='Critères de jugement')),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Appel d'offres",
                'verbose_name_plural': "Appels d'offres",
                'db_table': 'appels_offres_ao',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OffreEntreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('recue', 'Reçue'), ('non_conforme', 'Non conforme'), ('conforme', 'Conforme'), ('retenue', 'Retenue'), ('rejetee', 'Rejetée')], default='recue', max_length=20, verbose_name='Statut')),
                ('montant_offre_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Montant de l'offre HT (€)")),
                ('montant_negociee_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant négocié HT (€)')),
                ('delai_propose_jours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Délai proposé (jours ouvrés)')),
                ('notes_criteres', models.JSONField(blank=True, default=dict, help_text='{code_critere: note}', verbose_name='Notes par critère')),
                ('note_globale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note globale (/100)')),
                ('observations', models.TextField(blank=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Offre d'entreprise",
                'verbose_name_plural': "Offres d'entreprises",
                'db_table': 'appels_offres_offre',
                'ordering': ['appel_offres', 'note_globale'],
            },
        ),
    ]
