# Generated by Django 5.2.12 on 2026-03-27 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appels_offres', '0001_initial'),
        ('organisations', '0001_initial'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffres',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_offres', to='projets.lot', verbose_name='Lot'),
        ),
        migrations.AddField(
            model_name='appeloffres',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_offres', to='projets.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='offreentreprise',
            name='appel_offres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='appels_offres.appeloffres', verbose_name="Appel d'offres"),
        ),
        migrations.AddField(
            model_name='offreentreprise',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres_deposees', to='organisations.organisation', verbose_name='Entreprise soumissionnaire'),
        ),
        migrations.AlterUniqueTogether(
            name='offreentreprise',
            unique_together={('appel_offres', 'entreprise')},
        ),
    ]
