# Generated by Django on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appels_offres", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeloffres",
            name="analyse_contractuelle",
            field=models.TextField(blank=True, verbose_name="Analyse contractuelle"),
        ),
        migrations.AddField(
            model_name="appeloffres",
            name="conditions_paiement",
            field=models.TextField(blank=True, verbose_name="Conditions de paiement"),
        ),
        migrations.AddField(
            model_name="appeloffres",
            name="delai_execution_jours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Délai d'exécution visé (jours ouvrés)",
            ),
        ),
        migrations.AddField(
            model_name="appeloffres",
            name="garanties_exigees",
            field=models.TextField(blank=True, verbose_name="Garanties et assurances"),
        ),
        migrations.AddField(
            model_name="appeloffres",
            name="pieces_consultation",
            field=models.JSONField(blank=True, default=list, verbose_name="Pièces de consultation"),
        ),
        migrations.AddField(
            model_name="appeloffres",
            name="points_vigilance",
            field=models.JSONField(blank=True, default=list, verbose_name="Points de vigilance"),
        ),
        migrations.AddField(
            model_name="appeloffres",
            name="variantes_autorisees",
            field=models.BooleanField(default=False, verbose_name="Variantes autorisées"),
        ),
        migrations.AddField(
            model_name="offreentreprise",
            name="conformite_administrative",
            field=models.CharField(
                choices=[
                    ("a_verifier", "À vérifier"),
                    ("conforme", "Conforme"),
                    ("reserve", "Avec réserve"),
                    ("non_conforme", "Non conforme"),
                ],
                default="a_verifier",
                max_length=20,
                verbose_name="Conformité administrative",
            ),
        ),
        migrations.AddField(
            model_name="offreentreprise",
            name="conformite_technique",
            field=models.CharField(
                choices=[
                    ("a_verifier", "À vérifier"),
                    ("conforme", "Conforme"),
                    ("reserve", "Avec réserve"),
                    ("non_conforme", "Non conforme"),
                ],
                default="a_verifier",
                max_length=20,
                verbose_name="Conformité technique",
            ),
        ),
        migrations.AddField(
            model_name="offreentreprise",
            name="points_faibles",
            field=models.TextField(blank=True, verbose_name="Points faibles"),
        ),
        migrations.AddField(
            model_name="offreentreprise",
            name="points_forts",
            field=models.TextField(blank=True, verbose_name="Points forts"),
        ),
    ]
