# Generated by Django 5.2 on 2026-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0003_cadre_contractuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffres',
            name='parametres_analyse',
            field=models.JSONField(blank=True, default=dict, help_text="{methode_prix: '...', ...}", verbose_name="Paramètres d'analyse"),
        ),
        migrations.AddField(
            model_name='appeloffres',
            name='synthese_analyse',
            field=models.JSONField(blank=True, null=True, verbose_name="Synthèse de l'analyse comparative"),
        ),
    ]
