# Generated by Django 5.2 on 2026-04-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0004_ajoute_synthese_analyse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffres',
            name='synthese_analyse',
            field=models.JSONField(blank=True, default=dict, verbose_name="Synthèse de l'analyse comparative"),
        ),
    ]
