# Generated by Django 5.2.12 on 2026-03-27 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code organisation')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('type_organisation', models.CharField(choices=[('bureau_etudes', "Bureau d'études"), ('entreprise', 'Entreprise'), ('maitre_ouvrage', "Maître d'ouvrage"), ('partenaire', 'Partenaire'), ('sous_traitant', 'Sous-traitant')], max_length=30, verbose_name="Type d'organisation")),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='Numéro SIRET')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('courriel', models.EmailField(blank=True, max_length=254, verbose_name='Adresse de courriel')),
                ('site_web', models.CharField(blank=True, max_length=255, verbose_name='Site web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_organisations/', verbose_name='Logo')),
                ('est_active', models.BooleanField(default=True, verbose_name='Organisation active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('organisation_parente', models.ForeignKey(blank=True, help_text='Renseigner pour les agences et antennes rattachées à une structure mère.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations_filles', to='organisations.organisation', verbose_name='Organisation parente')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organisations_organisation',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='GroupeUtilisateurs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('membres', models.ManyToManyField(blank=True, related_name='groupes', to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='organisations.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Groupe d'utilisateurs",
                'verbose_name_plural': "Groupes d'utilisateurs",
                'db_table': 'organisations_groupe',
                'ordering': ['organisation', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'nom'), name='unicite_nom_groupe_par_organisation')],
            },
        ),
    ]
