# Generated by Django 5.2.12 on 2026-03-27 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LignePrixBibliotheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niveau', models.CharField(choices=[('reference', 'Prix de référence général'), ('territorial', 'Prix territorial'), ('entreprise', 'Prix entreprise'), ('affaire', 'Prix affaire'), ('negocie', 'Prix négocié'), ('constate', 'Prix constaté en bilan')], default='reference', max_length=30)),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('famille', models.CharField(max_length=100, verbose_name='Famille')),
                ('sous_famille', models.CharField(blank=True, max_length=100, verbose_name='Sous-famille')),
                ('corps_etat', models.CharField(blank=True, max_length=100, verbose_name="Corps d'état")),
                ('lot', models.CharField(blank=True, max_length=100, verbose_name='Lot')),
                ('designation_longue', models.TextField(verbose_name='Désignation longue')),
                ('designation_courte', models.CharField(max_length=300, verbose_name='Désignation courte')),
                ('unite', models.CharField(max_length=20, verbose_name='Unité')),
                ('hypotheses', models.TextField(blank=True, verbose_name='Hypothèses de calcul')),
                ('contexte_emploi', models.TextField(blank=True, verbose_name="Contexte d'emploi")),
                ('observations_techniques', models.TextField(blank=True)),
                ('observations_economiques', models.TextField(blank=True)),
                ('temps_main_oeuvre', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cout_horaire_mo', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cout_matieres', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cout_materiel', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cout_sous_traitance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cout_transport', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('debourse_sec_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('fiabilite', models.PositiveSmallIntegerField(default=3, help_text='1 = estimatif, 5 = issu de bilan réel', verbose_name='Indice de fiabilité (1-5)')),
                ('periode_validite_debut', models.DateField(blank=True, null=True)),
                ('periode_validite_fin', models.DateField(blank=True, null=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('statut_validation', models.CharField(choices=[('brouillon', 'Brouillon'), ('a_valider', 'À valider'), ('valide', 'Validé'), ('obsolete', 'Obsolète')], default='brouillon', max_length=30)),
                ('territoire', models.CharField(blank=True, max_length=100)),
                ('saison', models.CharField(blank=True, max_length=50)),
                ('coefficient_territoire', models.DecimalField(decimal_places=3, default=1.0, max_digits=5, verbose_name='Coefficient territorial')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ligne de bibliothèque de prix',
                'verbose_name_plural': 'Bibliothèque de prix',
                'db_table': 'bibliotheque_ligne_prix',
            },
        ),
    ]
