# Generated by Django 5.2.12 on 2026-03-27 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotheque', '0001_initial'),
        ('organisations', '0001_initial'),
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bibliotheque', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='ligne_parente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='bibliotheque.ligneprixbibliotheque', verbose_name='Version précédente'),
        ),
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bibliotheque_prix', to='organisations.organisation', verbose_name='Organisation (vide = référentiel général)'),
        ),
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bibliotheque_prix', to='projets.projet', verbose_name='Projet (pour niveau affaire)'),
        ),
        migrations.AddIndex(
            model_name='ligneprixbibliotheque',
            index=models.Index(fields=['famille', 'sous_famille'], name='bibliothequ_famille_cbe985_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneprixbibliotheque',
            index=models.Index(fields=['code'], name='bibliothequ_code_5d2a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneprixbibliotheque',
            index=models.Index(fields=['niveau', 'organisation'], name='bibliothequ_niveau_25f747_idx'),
        ),
    ]
