# Generated by Django 5.2 on 2026-04-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_sous_detail_prix'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sousdetailprix',
            new_name='bibliothequ_ligne_p_83796f_idx',
            old_name='bib_sdp_ligne_ordre_idx',
        ),
        migrations.RenameIndex(
            model_name='sousdetailprix',
            new_name='bibliothequ_type_re_969a84_idx',
            old_name='bib_sdp_type_ressource_idx',
        ),
    ]
