# Migration : ajout des champs de traçabilité source, structure CCTP et frais divers pour la bibliothèque de prix.
# Generated by Django 5.2.12 on 2026-04-02 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0005_ligneprixbibliotheque_donnees_analytiques'),
        ('organisations', '0001_initial'),
        ('projets', '0002_projet_type_projet_autre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='cahier_des_charges_structure',
            field=models.JSONField(blank=True, default=list, verbose_name='Structure du cahier des charges'),
        ),
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='code_source_externe',
            field=models.CharField(blank=True, max_length=80, verbose_name='Code source externe'),
        ),
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='cout_frais_divers',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='origine_import',
            field=models.CharField(choices=[('interne', 'Saisie interne'), ('bordereau_pdf', 'Bordereau PDF'), ('prix_construction', 'Prix Construction'), ('etude_prix', 'Étude de prix')], default='interne', max_length=30, verbose_name="Origine d'import"),
        ),
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='url_source',
            field=models.URLField(blank=True, verbose_name='URL source'),
        ),
        migrations.AddIndex(
            model_name='ligneprixbibliotheque',
            index=models.Index(fields=['origine_import', 'code_source_externe'], name='bibliothequ_origine_305ae3_idx'),
        ),
    ]
