# Generated by Django 5.2 on 2026-04-12 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0007_sousdetailprix_nombre_ressources_and_more'),
        ('pieces_ecrites', '0008_prescriptions_cctp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='caracteristiques_techniques',
            field=models.JSONField(blank=True, default=dict, help_text="Ex: {resistance: 'C25/30', granulometrie: '0/20', norme: 'NF EN 206'}", verbose_name='Caractéristiques techniques'),
        ),
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='conditions_mise_en_oeuvre',
            field=models.TextField(blank=True, verbose_name='Conditions de mise en œuvre'),
        ),
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='cout_consommables',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Consommables et fournitures accessoires (€/u HT)'),
        ),
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='lot_cctp_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_prix', to='pieces_ecrites.lotcctp', verbose_name='Lot CCTP de référence'),
        ),
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='prescriptions_liees',
            field=models.ManyToManyField(blank=True, related_name='lignes_prix', to='pieces_ecrites.prescriptioncctp', verbose_name='Prescriptions CCTP liées'),
        ),
    ]
