# Generated by Django 5.2 on 2026-04-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0008_ajout_consommables_prescriptions_cctp_caracteristiques'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneprixbibliotheque',
            name='illustrations',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'URLs d'images illustrant la prestation", verbose_name='Illustrations'),
        ),
    ]
