# Generated by Django 5.2 on 2026-05-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0010_controle_sdp_ds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousdetailprix',
            name='type_ressource',
            field=models.CharField(choices=[('mo', "Main-d'œuvre"), ('matiere', 'Matière / Fourniture'), ('materiel', 'Matériel / Engin'), ('consommable', 'Consommable'), ('sous_traitance', 'Sous-traitance'), ('transport', 'Transport'), ('frais_divers', 'Frais divers')], max_length=20, verbose_name='Type de ressource'),
        ),
    ]
