# Generated by Django 5.2.12 on 2026-03-27 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteSupervision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_alerte', models.CharField(choices=[('service_indisponible', 'Service indisponible'), ('performance_degradee', 'Performance dégradée'), ('espace_disque', 'Espace disque critique'), ('erreurs_repetees', 'Erreurs répétées'), ('tentatives_connexion', 'Tentatives de connexion suspectes'), ('tache_bloquee', 'Tâche Celery bloquée'), ('certificat_expiration', "Certificat SSL proche de l'expiration")], max_length=40)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('avertissement', 'Avertissement'), ('critique', 'Critique')], default='avertissement', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('service_concerne', models.CharField(blank=True, max_length=100)),
                ('est_active', models.BooleanField(default=True, verbose_name='Alerte active')),
                ('date_declenchement', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('acquittee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_acquittees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte de supervision',
                'verbose_name_plural': 'Alertes de supervision',
                'db_table': 'supervision_alerte',
                'ordering': ['-date_declenchement'],
            },
        ),
        migrations.CreateModel(
            name='MetriqueService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('backend', 'Cœur applicatif'), ('celery', 'File de tâches Celery'), ('postgresql', 'Base de données PostgreSQL'), ('redis', 'Cache Redis'), ('minio', 'Stockage MinIO'), ('frontend', 'Interface utilisateur')], max_length=30)),
                ('disponible', models.BooleanField(default=True, verbose_name='Service disponible')),
                ('temps_reponse_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Temps de réponse (ms)')),
                ('charge_cpu_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Charge CPU (%)')),
                ('memoire_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mémoire utilisée (%)')),
                ('details', models.JSONField(blank=True, null=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrique de service',
                'verbose_name_plural': 'Métriques de services',
                'db_table': 'supervision_metrique',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['service', 'horodatage'], name='supervision_service_d251aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvenementSysteme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niveau', models.CharField(choices=[('debug', 'Débogage'), ('info', 'Information'), ('avertissement', 'Avertissement'), ('erreur', 'Erreur'), ('critique', 'Critique')], default='info', max_length=20)),
                ('categorie', models.CharField(choices=[('securite', 'Sécurité'), ('performance', 'Performance'), ('erreur_applicative', 'Erreur applicative'), ('maintenance', 'Maintenance'), ('donnees', 'Données'), ('authentification', 'Authentification'), ('systeme', 'Système')], default='systeme', max_length=30)),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Détails techniques')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source (module, vue)')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_evenement', models.DateTimeField(auto_now_add=True)),
                ('resolu', models.BooleanField(default=False)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_systeme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement système',
                'verbose_name_plural': 'Événements système',
                'db_table': 'supervision_evenement',
                'ordering': ['-date_evenement'],
                'indexes': [models.Index(fields=['niveau', 'date_evenement'], name='supervision_niveau_13ca49_idx'), models.Index(fields=['categorie'], name='supervision_categor_a729aa_idx')],
            },
        ),
    ]
