# Generated by Django 5.2 on 2026-04-02 00:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantaneServeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_cpu_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Charge CPU (%)')),
                ('memoire_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Mémoire utilisée (%)')),
                ('disque_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Espace disque utilisé (%)')),
                ('charge_moyenne_1m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Charge moyenne 1 min')),
                ('charge_moyenne_5m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Charge moyenne 5 min')),
                ('charge_moyenne_15m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Charge moyenne 15 min')),
                ('memoire_totale_octets', models.BigIntegerField(blank=True, null=True, verbose_name='Mémoire totale (octets)')),
                ('memoire_utilisee_octets', models.BigIntegerField(blank=True, null=True, verbose_name='Mémoire utilisée (octets)')),
                ('disque_total_octets', models.BigIntegerField(blank=True, null=True, verbose_name='Espace disque total (octets)')),
                ('disque_utilise_octets', models.BigIntegerField(blank=True, null=True, verbose_name='Espace disque utilisé (octets)')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Détails')),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instantané serveur',
                'verbose_name_plural': 'Instantanés serveur',
                'db_table': 'supervision_instantane_serveur',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['horodatage'], name='supervision_horodat_c35f4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServeurMail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('hote', models.CharField(max_length=255, verbose_name='Hôte SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='Port')),
                ('chiffrement', models.CharField(choices=[('aucun', 'Aucun'), ('starttls', 'STARTTLS'), ('ssl_tls', 'SSL / TLS')], default='starttls', max_length=20, verbose_name='Chiffrement')),
                ('utilisateur', models.CharField(blank=True, max_length=255, verbose_name='Utilisateur')),
                ('mot_de_passe', models.TextField(blank=True, verbose_name='Mot de passe')),
                ('expediteur_defaut', models.EmailField(blank=True, max_length=254, verbose_name='Expéditeur par défaut')),
                ('reponse_a', models.EmailField(blank=True, max_length=254, verbose_name='Adresse de réponse')),
                ('delai_connexion', models.PositiveIntegerField(default=15, verbose_name='Délai de connexion (s)')),
                ('verifier_certificat', models.BooleanField(default=True, verbose_name='Vérifier le certificat TLS')),
                ('usage_envoi_plateforme', models.BooleanField(default=True, verbose_name='Envoi des courriels de la plateforme')),
                ('usage_notifications', models.BooleanField(default=True, verbose_name='Envoi des notifications')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Serveur actif')),
                ('est_defaut', models.BooleanField(default=False, verbose_name='Serveur par défaut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serveurs_mail_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Serveur de mail',
                'verbose_name_plural': 'Serveurs de mail',
                'db_table': 'supervision_serveur_mail',
                'ordering': ['-est_defaut', 'nom'],
                'indexes': [models.Index(fields=['est_actif', 'est_defaut'], name='supervision_est_act_f80958_idx'), models.Index(fields=['nom'], name='supervision_nom_96b180_idx')],
            },
        ),
    ]
