# Generated by Django 5.2.12 on 2026-03-27 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('type_document', models.CharField(choices=[('cctp', 'CCTP — Cahier des Clauses Techniques Particulières'), ('dpgf', 'DPGF — Décomposition du Prix Global et Forfaitaire'), ('bpu', 'BPU — Bordereau des Prix Unitaires'), ('dqe', 'DQE — Détail Quantitatif Estimatif'), ('rc', 'RC — Règlement de Consultation'), ('ae', "AE — Acte d'Engagement"), ('ccap', 'CCAP — Cahier des Clauses Administratives Particulières'), ('rapport', 'Rapport technique'), ('note_calcul', 'Note de calcul'), ('autre', 'Autre pièce écrite')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True)),
                ('gabarit', models.FileField(blank=True, null=True, upload_to='gabarits/', verbose_name='Fichier gabarit')),
                ('variables_fusion', models.JSONField(blank=True, default=list, help_text='Liste des variables {nom, description, exemple}', verbose_name='Variables de fusion disponibles')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
                'db_table': 'pieces_ecrites_modele',
                'ordering': ['type_document', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='PieceEcrite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=500, verbose_name='Intitulé')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_relecture', 'En relecture'), ('valide', 'Validée'), ('diffuse', 'Diffusée'), ('archive', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('contenu_html', models.TextField(blank=True, verbose_name='Contenu (HTML/Markdown)')),
                ('fichier_genere', models.FileField(blank=True, null=True, upload_to='pieces_ecrites/%Y/%m/', verbose_name='Fichier généré')),
                ('date_generation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projets.lot', verbose_name='Lot')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='pieces_ecrites.modeledocument', verbose_name='Modèle')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_ecrites', to='projets.projet', verbose_name='Projet')),
                ('redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pieces_ecrites_redigees', to=settings.AUTH_USER_MODEL, verbose_name='Rédacteur')),
            ],
            options={
                'verbose_name': 'Pièce écrite',
                'verbose_name_plural': 'Pièces écrites',
                'db_table': 'pieces_ecrites_piece',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCCTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapitre', models.CharField(blank=True, max_length=200, verbose_name='Chapitre')),
                ('numero_article', models.CharField(max_length=20, verbose_name="Numéro d'article")),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé')),
                ('corps_article', models.TextField(verbose_name="Corps de l'article")),
                ('normes_applicables', models.JSONField(blank=True, default=list, verbose_name='Normes applicables')),
                ('est_dans_bibliotheque', models.BooleanField(default=False, verbose_name='Disponible dans la bibliothèque')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('piece_ecrite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='pieces_ecrites.pieceecrite', verbose_name='Pièce écrite')),
            ],
            options={
                'verbose_name': 'Article CCTP',
                'verbose_name_plural': 'Articles CCTP',
                'db_table': 'pieces_ecrites_article_cctp',
                'ordering': ['chapitre', 'numero_article'],
            },
        ),
    ]
