# Generated by Django 5.2 on 2026-04-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_ecrites', '0004_modeles_document_metier_par_defaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeledocument',
            name='type_document',
            field=models.CharField(choices=[('cctp', 'CCTP — Cahier des Clauses Techniques Particulières'), ('dpgf', 'DPGF — Décomposition du Prix Global et Forfaitaire'), ('bpu', 'BPU — Bordereau des Prix Unitaires'), ('dqe', 'DQE — Détail Quantitatif Estimatif'), ('rc', 'RC — Règlement de Consultation'), ('ae', "AE — Acte d'Engagement"), ('ccap', 'CCAP — Cahier des Clauses Administratives Particulières'), ('lettre_candidature', 'Lettre de candidature'), ('memoire_technique', 'Mémoire technique'), ('planning_taches', 'Planning de tâches'), ('rapport_analyse', "Rapport d'analyse"), ('rapport', 'Rapport technique'), ('note_calcul', 'Note de calcul'), ('autre', 'Autre pièce écrite')], max_length=20, verbose_name='Type'),
        ),
    ]
