# Migration : enrichissement des articles CCTP avec leurs références LBH et le lien vers la bibliothèque de prix.
# Generated by Django 5.2.12 on 2026-04-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0006_ligneprixbibliotheque_cahier_des_charges_structure_and_more'),
        ('pieces_ecrites', '0005_alter_modeledocument_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecctp',
            name='code_reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code de référence'),
        ),
        migrations.AddField(
            model_name='articlecctp',
            name='ligne_prix_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_cctp', to='bibliotheque.ligneprixbibliotheque', verbose_name='Ligne de prix de référence'),
        ),
        migrations.AddField(
            model_name='articlecctp',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='articlecctp',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='URL source'),
        ),
    ]
