# Generated by Django 5.2 on 2026-04-03 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_dossierdocumentprojet_document_dossier_and_more'),
        ('pieces_ecrites', '0006_articlecctp_code_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceecrite',
            name='document_ged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_ecrites_sources', to='documents.document', verbose_name='Document GED lié'),
        ),
    ]
