# Generated by Django 5.2 on 2026-04-12 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_ecrites', '0007_pieceecrite_document_ged'),
        ('projets', '0005_prealyses_sources_et_organisation_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotCCTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(choices=[('7.1', '7.1 — VRD et réseaux'), ('7.2', '7.2 — Terrassements'), ('7.3', '7.3 — Gros Œuvre'), ('7.4', '7.4 — Façades et bardages'), ('7.5', '7.5 — Murs-rideaux'), ('7.6', '7.6 — Construction ossature bois'), ('7.7', '7.7 — Charpente métallique'), ('7.8', '7.8 — Charpente-Couverture-Zinguerie'), ('7.9', '7.9 — Étanchéité'), ('7.10', '7.10 — Menuiseries extérieures'), ('7.11', '7.11 — Menuiseries intérieures et serrurerie'), ('7.12', '7.12 — Isolation-Plâtrerie-Peinture'), ('7.13', '7.13 — Revêtements de sols et carrelage'), ('7.14', '7.14 — Électricité courants forts et faibles'), ('7.15', '7.15 — Plomberie sanitaires'), ('7.16', '7.16 — CVC — Chauffage Ventilation Climatisation'), ('7.17', '7.17 — Ascenseur et monte-charge'), ('7.18', '7.18 — Aménagements paysagers et espaces verts'), ('autre', 'Autre lot')], max_length=10, unique=True, verbose_name='Numéro de lot')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('normes_principales', models.JSONField(blank=True, default=list, verbose_name='Normes et DTU principaux')),
                ('est_actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lot CCTP',
                'verbose_name_plural': 'Lots CCTP',
                'db_table': 'pieces_ecrites_lot_cctp',
                'ordering': ['ordre', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ChapitrePrescrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro (ex: 1, 1.1, A)')),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé du chapitre')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='pieces_ecrites.lotcctp')),
            ],
            options={
                'verbose_name': 'Chapitre de prescription',
                'db_table': 'pieces_ecrites_chapitre_prescrip',
                'ordering': ['lot', 'ordre', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionCCTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Code')),
                ('intitule', models.CharField(max_length=400, verbose_name='Intitulé')),
                ('corps', models.TextField(verbose_name='Corps de la prescription')),
                ('type_prescription', models.CharField(choices=[('generalites', 'Généralités et objet du lot'), ('documents_reference', 'Documents de référence (DTU, NF, Eurocode)'), ('materiaux', 'Qualité et provenance des matériaux'), ('mise_en_oeuvre', 'Mise en œuvre et exécution'), ('controles', 'Contrôles et essais'), ('tolerances', "Tolérances d'exécution"), ('garanties', 'Garanties et assurances'), ('interfaces', 'Interfaces avec les autres lots'), ('reception', 'Conditions de réception'), ('entretien', 'Entretien et maintenance'), ('securite', 'Sécurité et protection'), ('environnement', 'Environnement et gestion des déchets')], default='mise_en_oeuvre', max_length=30, verbose_name='Type')),
                ('niveau', models.CharField(choices=[('obligatoire', 'Obligatoire — imposé par la norme ou le DTU'), ('recommande', 'Recommandé — bonne pratique'), ('alternatif', 'Alternatif — variante acceptable'), ('optionnel', 'Optionnel — à adapter selon le projet')], default='recommande', max_length=20, verbose_name='Niveau')),
                ('normes', models.JSONField(blank=True, default=list, verbose_name='Normes citées (DTU, NF, Eurocode)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Mots-clés')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('contient_variables', models.BooleanField(default=False, help_text='Cocher si le texte contient des variables entre accolades {variable}', verbose_name='Contient des variables')),
                ('est_actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pieces_ecrites.chapitreprescrip', verbose_name='Chapitre')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pieces_ecrites.lotcctp', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Prescription CCTP',
                'verbose_name_plural': 'Prescriptions CCTP',
                'db_table': 'pieces_ecrites_prescription_cctp',
                'ordering': ['lot', 'chapitre', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='GenerateurCCTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé du CCTP')),
                ('statut', models.CharField(choices=[('configuration', 'Configuration — sélection des lots'), ('redaction', 'Rédaction — personnalisation des prescriptions'), ('generation', 'Génération en cours'), ('termine', 'Terminé — document disponible'), ('erreur', 'Erreur lors de la génération')], default='configuration', max_length=20)),
                ('prescriptions_personnalisees', models.JSONField(blank=True, default=dict, help_text='Dictionnaire {uuid_prescription: texte_personnalisé}', verbose_name='Corps personnalisés par prescription')),
                ('variables_fusion', models.JSONField(blank=True, default=dict, help_text='{nom_projet, maitre_ouvrage, phase, date_redaction, ...}', verbose_name='Variables de fusion')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('piece_ecrite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generateurs_cctp', to='pieces_ecrites.pieceecrite', verbose_name='Pièce écrite générée')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generateurs_cctp', to='projets.projet', verbose_name='Projet')),
                ('lots_selectionnes', models.ManyToManyField(blank=True, related_name='generateurs', to='pieces_ecrites.lotcctp', verbose_name='Lots inclus')),
                ('prescriptions_exclues', models.ManyToManyField(blank=True, related_name='generateurs_exclus', to='pieces_ecrites.prescriptioncctp', verbose_name='Prescriptions exclues')),
            ],
            options={
                'verbose_name': 'Générateur CCTP',
                'verbose_name_plural': 'Générateurs CCTP',
                'db_table': 'pieces_ecrites_generateur_cctp',
                'ordering': ['-date_modification'],
            },
        ),
    ]
