# Generated by Django 5.2 on 2026-04-13 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_ecrites', '0009_restructure_lot_cctp_code_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecctp',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='pieces_ecrites.lotcctp', verbose_name='Lot CCTP'),
        ),
    ]
