# Generated by Django 5.2 on 2026-04-18 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_ecrites', '0010_articlecctp_lot_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneDPGF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('type_ligne', models.CharField(choices=[('lot', 'En-tête de lot'), ('article', 'Article / Prestation'), ('sous_total', 'Sous-total de chapitre'), ('commentaire', 'Commentaire / Note')], default='article', max_length=20, verbose_name='Type de ligne')),
                ('lot_code', models.CharField(blank=True, max_length=20, verbose_name='Code lot')),
                ('lot_intitule', models.CharField(blank=True, max_length=200, verbose_name='Intitulé lot')),
                ('numero', models.CharField(blank=True, max_length=30, verbose_name='Numéro')),
                ('designation', models.CharField(max_length=500, verbose_name='Désignation')),
                ('unite', models.CharField(blank=True, max_length=30, verbose_name='Unité')),
                ('quantite', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Quantité')),
                ('prix_unitaire_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Prix unitaire HT (€)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('piece_ecrite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_dpgf', to='pieces_ecrites.pieceecrite', verbose_name='Pièce écrite')),
            ],
            options={
                'verbose_name': 'Ligne DPGF/DQE',
                'verbose_name_plural': 'Lignes DPGF/DQE',
                'db_table': 'pieces_ecrites_ligne_dpgf',
                'ordering': ['piece_ecrite', 'ordre'],
            },
        ),
    ]
