# Generated by Django 5.2 on 2026-05-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces_ecrites', '0012_articlecctp_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecctp',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('a_verifier', 'À vérifier'), ('a_completer', 'À compléter — créé depuis le métré'), ('valide', 'Validé — article complet')], db_index=True, default='brouillon', max_length=20, verbose_name='Statut de complétion'),
        ),
    ]
