# Generated by Django 5.2.12 on 2026-03-27 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotheque', '0002_initial'),
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudeEconomique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=300, verbose_name="Intitulé de l'étude")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('a_valider', 'À valider'), ('validee', 'Validée'), ('archivee', 'Archivée')], default='brouillon', max_length=30)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('est_variante', models.BooleanField(default=False, verbose_name='Variante')),
                ('taux_frais_chantier', models.DecimalField(blank=True, decimal_places=4, help_text='Laisser vide pour utiliser le paramètre système', max_digits=6, null=True, verbose_name='Taux frais de chantier')),
                ('taux_frais_generaux', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Taux frais généraux')),
                ('taux_aleas', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name="Taux d'aléas")),
                ('taux_marge_cible', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Taux de marge cible')),
                ('taux_pertes', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Taux de pertes matières')),
                ('total_debourse_sec', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cout_direct', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cout_revient', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_marge_brute', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_marge_nette', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_marge_nette_global', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('etude_parente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes', to='economie.etudeeconomique', verbose_name='Étude de base')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudes', to='projets.lot')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudes_economiques', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Étude économique',
                'verbose_name_plural': 'Études économiques',
                'db_table': 'economie_etude_economique',
            },
        ),
        migrations.CreateModel(
            name='LignePrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ordre', models.PositiveSmallIntegerField(default=1, verbose_name="N° d'ordre")),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code')),
                ('designation', models.TextField(verbose_name='Désignation')),
                ('unite', models.CharField(default='u', max_length=20, verbose_name='Unité')),
                ('quantite_prevue', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantité prévue')),
                ('quantite_reelle', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Quantité réelle')),
                ('temps_main_oeuvre', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Temps MO (h/unité)')),
                ('cout_horaire_mo', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Coût horaire MO (€/h)')),
                ('cout_matieres', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Coût matières unitaire (€/u)')),
                ('cout_materiel', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Coût matériel unitaire (€/u)')),
                ('cout_sous_traitance', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Coût sous-traitance unitaire (€/u)')),
                ('cout_transport', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Coût transport unitaire (€/u)')),
                ('taux_pertes_surcharge', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('taux_frais_chantier_surcharge', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('taux_frais_generaux_surcharge', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('taux_aleas_surcharge', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('taux_marge_surcharge', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('debourse_sec_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cout_direct_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cout_revient_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('marge_brute_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('marge_nette_unitaire', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('taux_marge_nette', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('marge_brute_totale', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('marge_nette_totale', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('contribution_marge', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Contribution à la marge du lot (%)')),
                ('etat_rentabilite', models.CharField(choices=[('rentable', 'Rentable'), ('surveiller', 'À surveiller'), ('faible', 'Faiblement rentable'), ('non_rentable', 'Non rentable'), ('sous_condition', 'Rentable sous condition'), ('deficitaire_origine', "Déficitaire dès l'origine"), ('indefini', 'Non calculé')], default='indefini', max_length=30, verbose_name='État de rentabilité')),
                ('seuil_quantite_critique', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Quantité critique (seuil de rentabilité nulle)')),
                ('seuil_prix_minimum', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Prix de vente minimum (rentabilité nulle)')),
                ('indice_sensibilite_quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('indice_sensibilite_main_oeuvre', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('indice_sensibilite_matieres', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('causes_non_rentabilite', models.JSONField(blank=True, default=list)),
                ('observations', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='economie.etudeeconomique')),
                ('ref_bibliotheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisations', to='bibliotheque.ligneprixbibliotheque')),
            ],
            options={
                'verbose_name': 'Ligne de prix',
                'verbose_name_plural': 'Lignes de prix',
                'db_table': 'economie_ligne_prix',
                'ordering': ['etude', 'numero_ordre'],
            },
        ),
    ]
