# Generated by Django 5.2 on 2026-04-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economie', '0002_etude_prix_lignes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='etudeprix',
            new_name='economie_et_statut_90433d_idx',
            old_name='eco_ep_statut_millesime_idx',
        ),
        migrations.RenameIndex(
            model_name='etudeprix',
            new_name='economie_et_lot_typ_63b666_idx',
            old_name='eco_ep_lot_type_idx',
        ),
    ]
