from decimal import Decimal
import django.db.models.deletion
from django.db import migrations, models


def initialiser_taxonomie_main_oeuvre(apps, schema_editor):
    ProfilMainOeuvre = apps.get_model("economie", "ProfilMainOeuvre")
    LignePrixEtude = apps.get_model("economie", "LignePrixEtude")

    for ligne in LignePrixEtude.objects.filter(type_ressource="mo"):
        updates = []
        if not ligne.nombre_ressources:
            ligne.nombre_ressources = Decimal("1")
            updates.append("nombre_ressources")
        if not ligne.temps_unitaire and ligne.quantite:
            ligne.temps_unitaire = ligne.quantite
            updates.append("temps_unitaire")
        if updates:
            ligne.save(update_fields=updates)

    source_ouvriers = "https://www.legifrance.gouv.fr/conv_coll/article/KALIARTI000005778257"
    source_etam = "https://www.legifrance.gouv.fr/conv_coll/id/KALIARTI000018773721"
    source_cadres = "https://www.legifrance.gouv.fr/conv_coll/id/KALIARTI000017941868"

    profils = [
        {
            "code": "MANOEUVRE_BTP",
            "libelle": "Manœuvre chantier BTP",
            "categorie": "ouvrier",
            "secteur_activite": "batiment",
            "metier": "Manœuvre",
            "niveau_classification": "Ouvrier d'exécution",
            "fonction_equipe": "Exécution",
            "description_emploi": "Main-d'œuvre polyvalente d'approvisionnement, manutention et aide à la mise en œuvre.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("1850.00"),
            "taux_charges_patronales": Decimal("0.3800"),
            "cout_equipement_mensuel": Decimal("70.00"),
            "cout_transport_mensuel": Decimal("60.00"),
            "ordre_affichage": 5,
        },
        {
            "code": "MACON_CP2",
            "libelle": "Compagnon professionnel maçon",
            "categorie": "compagnon",
            "secteur_activite": "batiment",
            "metier": "Maçon",
            "specialite": "Gros œuvre",
            "niveau_classification": "CP2",
            "fonction_equipe": "Compagnon",
            "description_emploi": "Réalisation de maçonneries courantes, ouvrages en béton et reprises structurelles.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2350.00"),
            "taux_charges_patronales": Decimal("0.4000"),
            "cout_equipement_mensuel": Decimal("95.00"),
            "cout_transport_mensuel": Decimal("80.00"),
            "ordre_affichage": 10,
        },
        {
            "code": "COFFREUR_BANCHEUR_CP2",
            "libelle": "Compagnon professionnel coffreur-bancheur",
            "categorie": "compagnon",
            "secteur_activite": "batiment",
            "metier": "Coffreur-bancheur",
            "specialite": "Béton armé",
            "niveau_classification": "CP2",
            "fonction_equipe": "Compagnon",
            "description_emploi": "Pose de coffrages, banches, réservations et coulage des ouvrages en béton armé.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2450.00"),
            "taux_charges_patronales": Decimal("0.4050"),
            "cout_equipement_mensuel": Decimal("100.00"),
            "cout_transport_mensuel": Decimal("85.00"),
            "ordre_affichage": 12,
        },
        {
            "code": "FERRAILLEUR_CP2",
            "libelle": "Compagnon professionnel ferrailleur",
            "categorie": "compagnon",
            "secteur_activite": "batiment",
            "metier": "Ferrailleur",
            "specialite": "Armatures béton armé",
            "niveau_classification": "CP2",
            "fonction_equipe": "Compagnon",
            "description_emploi": "Façonnage, assemblage et pose d'armatures pour ouvrages en béton armé.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2425.00"),
            "taux_charges_patronales": Decimal("0.4050"),
            "cout_equipement_mensuel": Decimal("95.00"),
            "cout_transport_mensuel": Decimal("80.00"),
            "ordre_affichage": 14,
        },
        {
            "code": "CANALISATEUR_VRD_CP2",
            "libelle": "Compagnon professionnel canalisateur VRD",
            "categorie": "compagnon",
            "secteur_activite": "vrd",
            "metier": "Canalisateur",
            "specialite": "VRD",
            "niveau_classification": "CP2",
            "fonction_equipe": "Compagnon",
            "description_emploi": "Pose de réseaux enterrés, regards, branchements et ouvrages VRD associés.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2400.00"),
            "taux_charges_patronales": Decimal("0.4020"),
            "cout_equipement_mensuel": Decimal("95.00"),
            "cout_transport_mensuel": Decimal("95.00"),
            "ordre_affichage": 16,
        },
        {
            "code": "CONDUCTEUR_PELLE_VRD",
            "libelle": "Conducteur d'engin pelle hydraulique",
            "categorie": "ouvrier",
            "secteur_activite": "vrd",
            "metier": "Conducteur d'engin",
            "specialite": "Pelle hydraulique",
            "niveau_classification": "Ouvrier professionnel",
            "fonction_equipe": "Conduite d'engin",
            "description_emploi": "Conduite de pelle pour terrassements, tranchées et manutentions chantier.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2550.00"),
            "taux_charges_patronales": Decimal("0.3980"),
            "cout_equipement_mensuel": Decimal("120.00"),
            "cout_transport_mensuel": Decimal("85.00"),
            "ordre_affichage": 18,
        },
        {
            "code": "CHARPENTIER_CP2",
            "libelle": "Compagnon professionnel charpentier",
            "categorie": "compagnon",
            "secteur_activite": "batiment",
            "metier": "Charpentier",
            "specialite": "Structure bois",
            "niveau_classification": "CP2",
            "fonction_equipe": "Compagnon",
            "description_emploi": "Taille, assemblage et pose de charpentes bois et éléments structurels associés.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2450.00"),
            "taux_charges_patronales": Decimal("0.4050"),
            "cout_equipement_mensuel": Decimal("100.00"),
            "cout_transport_mensuel": Decimal("80.00"),
            "ordre_affichage": 20,
        },
        {
            "code": "COUVREUR_CP2",
            "libelle": "Compagnon professionnel couvreur-zingueur",
            "categorie": "compagnon",
            "secteur_activite": "batiment",
            "metier": "Couvreur-zingueur",
            "specialite": "Couverture",
            "niveau_classification": "CP2",
            "fonction_equipe": "Compagnon",
            "description_emploi": "Pose des couvertures, accessoires d'étanchéité et ouvrages de zinguerie.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2500.00"),
            "taux_charges_patronales": Decimal("0.4080"),
            "cout_equipement_mensuel": Decimal("110.00"),
            "cout_transport_mensuel": Decimal("80.00"),
            "ordre_affichage": 22,
        },
        {
            "code": "ETANCHEUR_CP2",
            "libelle": "Compagnon professionnel étancheur",
            "categorie": "compagnon",
            "secteur_activite": "batiment",
            "metier": "Étancheur",
            "specialite": "Toitures-terrasses",
            "niveau_classification": "CP2",
            "fonction_equipe": "Compagnon",
            "description_emploi": "Mise en œuvre des complexes d'étanchéité, relevés et protections associées.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2475.00"),
            "taux_charges_patronales": Decimal("0.4070"),
            "cout_equipement_mensuel": Decimal("110.00"),
            "cout_transport_mensuel": Decimal("78.00"),
            "ordre_affichage": 24,
        },
        {
            "code": "PLAQUISTE_CP2",
            "libelle": "Compagnon professionnel plaquiste",
            "categorie": "compagnon",
            "secteur_activite": "batiment",
            "metier": "Plaquiste",
            "specialite": "Cloisons et doublages",
            "niveau_classification": "CP2",
            "fonction_equipe": "Compagnon",
            "description_emploi": "Pose de cloisons, doublages, plafonds et ouvrages de plâtrerie sèche.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2300.00"),
            "taux_charges_patronales": Decimal("0.4000"),
            "cout_equipement_mensuel": Decimal("85.00"),
            "cout_transport_mensuel": Decimal("70.00"),
            "ordre_affichage": 26,
        },
        {
            "code": "MENUISIER_EXT_CP2",
            "libelle": "Compagnon professionnel menuisier poseur",
            "categorie": "compagnon",
            "secteur_activite": "batiment",
            "metier": "Menuisier poseur",
            "specialite": "Menuiseries extérieures",
            "niveau_classification": "CP2",
            "fonction_equipe": "Compagnon",
            "description_emploi": "Pose de menuiseries extérieures, fermetures et accessoires de finition.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2380.00"),
            "taux_charges_patronales": Decimal("0.4020"),
            "cout_equipement_mensuel": Decimal("85.00"),
            "cout_transport_mensuel": Decimal("75.00"),
            "ordre_affichage": 28,
        },
        {
            "code": "ELECTRICIEN_CP2",
            "libelle": "Compagnon professionnel électricien",
            "categorie": "compagnon",
            "secteur_activite": "batiment",
            "metier": "Électricien",
            "specialite": "Courants forts et faibles",
            "niveau_classification": "CP2",
            "fonction_equipe": "Compagnon",
            "description_emploi": "Cheminements, câblages, appareillages, essais et mises en service courants forts/faibles.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2450.00"),
            "taux_charges_patronales": Decimal("0.4040"),
            "cout_equipement_mensuel": Decimal("90.00"),
            "cout_transport_mensuel": Decimal("75.00"),
            "ordre_affichage": 30,
        },
        {
            "code": "PLOMBIER_CVC_CP2",
            "libelle": "Compagnon professionnel plombier-chauffagiste",
            "categorie": "compagnon",
            "secteur_activite": "batiment",
            "metier": "Plombier-chauffagiste",
            "specialite": "Plomberie / CVC",
            "niveau_classification": "CP2",
            "fonction_equipe": "Compagnon",
            "description_emploi": "Réseaux sanitaires, chauffage et terminaux techniques courants.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2480.00"),
            "taux_charges_patronales": Decimal("0.4040"),
            "cout_equipement_mensuel": Decimal("95.00"),
            "cout_transport_mensuel": Decimal("78.00"),
            "ordre_affichage": 32,
        },
        {
            "code": "CHEF_EQUIPE_BTP",
            "libelle": "Chef d'équipe chantier BTP",
            "categorie": "compagnon",
            "secteur_activite": "batiment",
            "metier": "Chef d'équipe",
            "niveau_classification": "Maître-ouvrier / chef d'équipe",
            "fonction_equipe": "Encadrement de proximité",
            "description_emploi": "Coordination opérationnelle d'une équipe de production et contrôle de l'exécution.",
            "source_officielle": source_ouvriers,
            "salaire_brut_mensuel_defaut": Decimal("2850.00"),
            "taux_charges_patronales": Decimal("0.4100"),
            "cout_equipement_mensuel": Decimal("110.00"),
            "cout_transport_mensuel": Decimal("95.00"),
            "ordre_affichage": 34,
        },
        {
            "code": "TECHNICIEN_ETUDES",
            "libelle": "Technicien études",
            "categorie": "technicien",
            "secteur_activite": "maitrise_oeuvre",
            "metier": "Technicien études",
            "niveau_classification": "ETAM",
            "fonction_equipe": "Études et métrés",
            "description_emploi": "Préparation des quantitatifs, consultations et assistance aux études de prix.",
            "source_officielle": source_etam,
            "ordre_affichage": 40,
        },
        {
            "code": "ECONOMISTE_LBH",
            "libelle": "Économiste de la construction",
            "categorie": "economiste",
            "secteur_activite": "maitrise_oeuvre",
            "metier": "Économiste de la construction",
            "niveau_classification": "ETAM / cadre selon structure",
            "fonction_equipe": "Estimation et pièces écrites",
            "description_emploi": "Estimation analytique, DCE, CCTP et analyse des offres.",
            "source_officielle": source_etam,
            "ordre_affichage": 42,
        },
        {
            "code": "INGENIEUR_PROJET",
            "libelle": "Ingénieur projet",
            "categorie": "ingenieur",
            "secteur_activite": "maitrise_oeuvre",
            "metier": "Ingénieur projet",
            "niveau_classification": "Cadre",
            "fonction_equipe": "Pilotage technique",
            "description_emploi": "Coordination des études, arbitrages techniques et synthèse de projet.",
            "source_officielle": source_cadres,
            "ordre_affichage": 44,
        },
    ]

    for profil in profils:
        ProfilMainOeuvre.objects.update_or_create(code=profil["code"], defaults=profil)


class Migration(migrations.Migration):

    dependencies = [
        ('economie', '0006_references_sociales_et_variantes_locales'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneprixetude',
            name='nombre_ressources',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Effectif mobilisé sur la ressource analytique.', max_digits=8, verbose_name='Nombre de ressources'),
        ),
        migrations.AddField(
            model_name='ligneprixetude',
            name='profil_main_oeuvre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_etudes_prix', to='economie.profilmainoeuvre', verbose_name="Profil de main-d'œuvre"),
        ),
        migrations.AddField(
            model_name='ligneprixetude',
            name='temps_unitaire',
            field=models.DecimalField(decimal_places=6, default=0, help_text="Temps nécessaire par type d'ouvrier ou salarié pour une unité d'ouvrage.", max_digits=12, verbose_name='Temps unitaire (h)'),
        ),
        migrations.AddField(
            model_name='profilmainoeuvre',
            name='description_emploi',
            field=models.TextField(blank=True, verbose_name="Description d'emploi"),
        ),
        migrations.AddField(
            model_name='profilmainoeuvre',
            name='fonction_equipe',
            field=models.CharField(blank=True, max_length=120, verbose_name="Fonction dans l'équipe"),
        ),
        migrations.AddField(
            model_name='profilmainoeuvre',
            name='metier',
            field=models.CharField(blank=True, max_length=120, verbose_name='Métier'),
        ),
        migrations.AddField(
            model_name='profilmainoeuvre',
            name='niveau_classification',
            field=models.CharField(blank=True, max_length=120, verbose_name='Niveau / position'),
        ),
        migrations.AddField(
            model_name='profilmainoeuvre',
            name='secteur_activite',
            field=models.CharField(choices=[('batiment', 'Bâtiment'), ('vrd', 'Voirie et réseaux divers'), ('maitrise_oeuvre', "Maîtrise d'œuvre / études"), ('entreprise_generale', 'Entreprise générale'), ('support', 'Support chantier / structure'), ('autre', 'Autre')], default='batiment', max_length=30, verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='profilmainoeuvre',
            name='source_officielle',
            field=models.URLField(blank=True, verbose_name='Source officielle'),
        ),
        migrations.AddField(
            model_name='profilmainoeuvre',
            name='specialite',
            field=models.CharField(blank=True, max_length=120, verbose_name='Spécialité'),
        ),
        migrations.RunPython(initialiser_taxonomie_main_oeuvre, migrations.RunPython.noop),
    ]
