# Generated by Django 5.2 on 2026-04-03 17:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economie', '0007_ligneprixetude_nombre_ressources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudeprix',
            name='coefficient_k',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='etudeprix',
            name='cout_revient_ht',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='etudeprix',
            name='marge_previsionnelle_ht',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='etudeprix',
            name='montant_aleas_ht',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='etudeprix',
            name='montant_frais_chantier_ht',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='etudeprix',
            name='montant_frais_generaux_ht',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='etudeprix',
            name='prix_vente_ht',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='etudeprix',
            name='seuil_rentabilite_ht',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='etudeprix',
            name='taux_aleas',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0300'), max_digits=6, verbose_name="Taux d'aléas"),
        ),
        migrations.AddField(
            model_name='etudeprix',
            name='taux_frais_chantier',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0800'), max_digits=6, verbose_name='Taux frais de chantier'),
        ),
        migrations.AddField(
            model_name='etudeprix',
            name='taux_frais_generaux',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1200'), max_digits=6, verbose_name='Taux frais généraux'),
        ),
        migrations.AddField(
            model_name='etudeprix',
            name='taux_marge_cible',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=6, verbose_name='Taux de marge cible'),
        ),
        migrations.CreateModel(
            name='AchatEtudePrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.PositiveSmallIntegerField(default=1, verbose_name='Ordre')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('fournisseur', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('reference_fournisseur', models.CharField(blank=True, max_length=80, verbose_name='Référence fournisseur')),
                ('unite_achat', models.CharField(default='u', max_length=30, verbose_name="Unité d'achat")),
                ('quantite_besoin', models.DecimalField(decimal_places=6, default=1, max_digits=14)),
                ('quantite_conditionnement', models.DecimalField(decimal_places=6, default=1, max_digits=14)),
                ('nombre_conditionnements', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('quantite_commandee', models.DecimalField(decimal_places=6, default=1, max_digits=14)),
                ('prix_unitaire_achat_ht', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('cout_total_achat_ht', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('surcout_conditionnement_ht', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='economie.etudeprix', verbose_name='Étude de prix')),
                ('ligne_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats_proposes', to='economie.ligneprixetude', verbose_name='Ligne de ressource source')),
            ],
            options={
                'verbose_name': "Achat d'étude de prix",
                'verbose_name_plural': "Achats d'étude de prix",
                'db_table': 'economie_achat_etude_prix',
                'ordering': ['etude', 'ordre', 'designation'],
            },
        ),
    ]
