# Generated by Django 5.2 on 2026-04-12 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economie', '0008_etudeprix_coefficient_k_etudeprix_cout_revient_ht_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionEconomique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('estimation_tce', 'Estimation TCE — avant-projet'), ('dpgf_lots', 'DPGF — Décomposition du Prix Global par lot'), ('dqe_consultation', 'DQE — Détail Quantitatif Estimatif de consultation'), ('analyse_offres', 'Analyse comparative des offres reçues'), ('suivi_dgd', 'DGD — Suivi et liquidation du Décompte Général Définitif'), ('revision_prix', 'Révision de prix — formule paramétrique'), ('controle_situation', 'Contrôle des situations de travaux'), ('honoraires_moe', 'Calcul des honoraires MOE'), ('planning_mission', 'Planning de mission et jalons'), ('rapport_avancement', "Rapport d'avancement mensuel"), ('mission_opc', 'Mission OPC — pilotage chantier'), ('etude_prix_analytique', 'Étude de prix analytique — DS→PV'), ('reponse_ao', "Réponse à appel d'offres — BPU/DQE"), ('marge_lot', 'Analyse de marge par lot'), ('situation_travaux', 'Établissement des situations de travaux')], max_length=40, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('types_clients', models.JSONField(default=list, help_text='Liste des types de clients concernés : moa_public, moe, entreprise_btp')),
                ('est_actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mission économique',
                'db_table': 'economie_mission_economique',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DecompositionPrixInverse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=300, verbose_name="Désignation de l'ouvrage")),
                ('lot_type', models.CharField(blank=True, max_length=10, verbose_name="Lot / Corps d'état")),
                ('unite', models.CharField(default='u', max_length=20)),
                ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('prix_vente_unitaire_saisi', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Prix de vente unitaire HT saisi (€/unité)')),
                ('methode', models.CharField(choices=[('ratios_artiprix', "Ratios ARTIPRIX 2025 — par lot/corps d'état"), ('ratios_manuels', 'Ratios manuels — valeurs saisies'), ('conventions_btp', 'Conventions collectives BTP — taux standards')], default='ratios_artiprix', max_length=30)),
                ('kpv_estime', models.DecimalField(blank=True, decimal_places=4, help_text='PV = DS × Kpv. Kpv = 1 / (1 - taux_marge - taux_FG - taux_FC - taux_B&A)', max_digits=6, null=True, verbose_name='Coefficient de vente Kpv estimé')),
                ('taux_mo_estime', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Part MO dans DS (%)')),
                ('taux_matieres_estime', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Part matières dans DS (%)')),
                ('taux_materiel_estime', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Part matériel dans DS (%)')),
                ('taux_sous_traitance_estime', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Part sous-traitance dans DS (%)')),
                ('debourse_sec_unitaire_calcule', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cout_direct_unitaire_calcule', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cout_revient_unitaire_calcule', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('marge_unitaire_calculee', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('taux_marge_calcule', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('k_fc', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Kfc (frais chantier)')),
                ('k_fg', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Kfg (frais généraux)')),
                ('k_ba', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Kba (bénéfices et aléas)')),
                ('k_total', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Kpv total')),
                ('source_ratios', models.JSONField(blank=True, default=dict, verbose_name='Source et détail des ratios utilisés')),
                ('commentaire', models.TextField(blank=True)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('calcule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decompositions_inverses', to='economie.etudeeconomique')),
                ('etude_prix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decompositions_inverses', to='economie.etudeprix')),
            ],
            options={
                'verbose_name': 'Décomposition inverse de prix',
                'db_table': 'economie_decomposition_prix_inverse',
                'ordering': ['-date_calcul'],
            },
        ),
    ]
