# Generated by Django 5.2 on 2026-04-13 01:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economie', '0009_type_client_decomposition_inverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilmainoeuvre',
            name='jours_travail_mensuels_defaut',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.67'), help_text='Nombre moyen de jours travaillés par mois (base 260 j / 12).', max_digits=5, verbose_name='Jours de travail mensuels'),
        ),
        migrations.AddField(
            model_name='profilmainoeuvre',
            name='nb_heures_supp_25_mensuelles',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Nombre d'heures supplémentaires mensuelles majorées à 25 %.", max_digits=6, verbose_name='HS majorées à 25 % (h/mois)'),
        ),
        migrations.AddField(
            model_name='profilmainoeuvre',
            name='nb_heures_supp_50_mensuelles',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Nombre d'heures supplémentaires mensuelles majorées à 50 % (dimanches, fériés).", max_digits=6, verbose_name='HS majorées à 50 % (h/mois)'),
        ),
        migrations.AddField(
            model_name='profilmainoeuvre',
            name='panier_repas_journalier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant journalier du panier ou titre-restaurant employeur.', max_digits=8, verbose_name='Panier repas journalier (€)'),
        ),
    ]
