# Generated by Django 5.2 on 2026-04-13 02:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economie', '0010_profil_mo_hs_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilmainoeuvre',
            name='corps_etat',
            field=models.CharField(blank=True, help_text="Corps d'état BTP auquel ce profil est rattaché (ex : Gros Œuvre, Menuiseries, Électricité…).", max_length=120, verbose_name="Corps d'état"),
        ),
        migrations.AlterField(
            model_name='profilmainoeuvre',
            name='nb_heures_supp_25_mensuelles',
            field=models.DecimalField(decimal_places=2, default=Decimal('17.33'), help_text="Nombre d'heures supplémentaires mensuelles majorées à 25 % (base 39h/semaine BTP).", max_digits=6, verbose_name='HS majorées à 25 % (h/mois)'),
        ),
        migrations.AlterField(
            model_name='profilmainoeuvre',
            name='panier_repas_journalier',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='Montant journalier du panier repas (zone BTP, base conventionnelle).', max_digits=8, verbose_name='Panier repas journalier (€)'),
        ),
    ]
