# Generated by Django 5.2 on 2026-04-19 03:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economie', '0011_profil_mo_corps_etat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelePhaseEtudeEconomique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveSmallIntegerField(default=10, verbose_name='Ordre')),
                ('role_intervenant', models.CharField(choices=[('responsable', 'Responsable'), ('charge_affaires', "Chargé d'affaires"), ('economiste', 'Économiste'), ('redacteur', 'Rédacteur'), ('verificateur', 'Vérificateur'), ('conducteur_travaux', 'Conducteur de travaux')], default='economiste', max_length=30, verbose_name="Type d'intervenant")),
                ('specialite_requise', models.CharField(blank=True, max_length=120, verbose_name='Spécialité requise')),
                ('niveau_intervention', models.CharField(blank=True, max_length=120, verbose_name="Niveau d'intervention")),
                ('duree_previsionnelle_jours', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, verbose_name='Durée prévisionnelle (jours)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('profil_main_oeuvre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles_phases_etudes', to='economie.profilmainoeuvre', verbose_name='Profil DHMO conseillé')),
            ],
            options={
                'verbose_name': "Modèle de phase d'étude",
                'verbose_name_plural': "Modèles de phases d'étude",
                'db_table': 'economie_modele_phase_etude',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='PhaseEtudeEconomique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveSmallIntegerField(default=10, verbose_name='Ordre')),
                ('role_intervenant', models.CharField(choices=[('responsable', 'Responsable'), ('charge_affaires', "Chargé d'affaires"), ('economiste', 'Économiste'), ('redacteur', 'Rédacteur'), ('verificateur', 'Vérificateur'), ('conducteur_travaux', 'Conducteur de travaux')], default='economiste', max_length=30, verbose_name="Type d'intervenant")),
                ('specialite_requise', models.CharField(blank=True, max_length=120, verbose_name='Spécialité requise')),
                ('niveau_intervention', models.CharField(blank=True, max_length=120, verbose_name="Niveau d'intervention")),
                ('duree_previsionnelle_jours', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, verbose_name='Durée prévisionnelle (jours)')),
                ('duree_revisee_jours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Durée révisée (jours)')),
                ('statut', models.CharField(choices=[('a_planifier', 'À planifier'), ('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('bloquee', 'Bloquée')], default='a_planifier', max_length=20)),
                ('motif_dernier_ajustement', models.TextField(blank=True, verbose_name='Motif du dernier ajustement')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases_planification', to='economie.etudeeconomique', verbose_name='Étude économique')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases_instances', to='economie.modelephaseetudeeconomique', verbose_name='Modèle de phase')),
                ('profil_main_oeuvre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases_etudes_economiques', to='economie.profilmainoeuvre', verbose_name='Profil DHMO conseillé')),
                ('utilisateur_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases_etudes_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateur assigné')),
            ],
            options={
                'verbose_name': "Phase d'étude économique",
                'verbose_name_plural': "Phases d'études économiques",
                'db_table': 'economie_phase_etude',
                'ordering': ['ordre', 'date_creation'],
                'unique_together': {('etude', 'code', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='JournalPhaseEtudeEconomique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancienne_duree_jours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nouvelle_duree_jours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('motif', models.TextField(verbose_name='Motif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_phases_etudes', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_ajustements', to='economie.phaseetudeeconomique', verbose_name='Phase')),
            ],
            options={
                'verbose_name': "Journal de phase d'étude",
                'verbose_name_plural': "Journal des phases d'étude",
                'db_table': 'economie_journal_phase_etude',
                'ordering': ['-date_creation'],
            },
        ),
    ]
