# Generated by Django 5.2 on 2026-05-01 22:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economie', '0012_modelephaseetudeeconomique_phaseetudeeconomique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilleDecompositionPrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('mots_cles', models.JSONField(blank=True, default=list)),
                ('ratio_main_oeuvre', models.DecimalField(decimal_places=4, default=Decimal('0.4000'), max_digits=6)),
                ('ratio_materiaux', models.DecimalField(decimal_places=4, default=Decimal('0.3500'), max_digits=6)),
                ('ratio_materiel', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=6)),
                ('ratio_sous_traitance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6)),
                ('ratio_transport', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=6)),
                ('ratio_frais_divers', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=6)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Famille de décomposition de prix',
                'verbose_name_plural': 'Familles de décomposition de prix',
                'db_table': 'economie_famille_decomposition_prix',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='ParametreMoteurPrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('seuil_similarite', models.DecimalField(decimal_places=4, default=Decimal('0.6500'), max_digits=6)),
                ('seuil_ecart_prix_marche', models.DecimalField(decimal_places=4, default=Decimal('0.2500'), max_digits=6)),
                ('seuil_k_bas', models.DecimalField(decimal_places=4, default=Decimal('1.1000'), max_digits=8)),
                ('seuil_k_haut', models.DecimalField(decimal_places=4, default=Decimal('2.8000'), max_digits=8)),
                ('seuil_marge_faible', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=6)),
                ('seuil_anomalie_montant', models.DecimalField(decimal_places=4, default=Decimal('8.0000'), max_digits=8)),
                ('ponderations_strategies', models.JSONField(blank=True, default=dict)),
                ('facteur_mayotte', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=8)),
                ('mode_marge', models.CharField(choices=[('taux_marque', 'Taux de marque'), ('marge_sur_cout', 'Marge sur coût')], default='taux_marque', max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre du moteur de prix',
                'verbose_name_plural': 'Paramètres du moteur de prix',
                'db_table': 'economie_parametre_moteur_prix',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PlageCoefficientK',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('famille', models.CharField(blank=True, default='', max_length=120)),
                ('localite', models.CharField(blank=True, default='', max_length=120)),
                ('k_min', models.DecimalField(decimal_places=4, default=Decimal('1.1000'), max_digits=8)),
                ('k_max', models.DecimalField(decimal_places=4, default=Decimal('2.8000'), max_digits=8)),
                ('commentaire', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plage de coefficient K',
                'verbose_name_plural': 'Plages de coefficients K',
                'db_table': 'economie_plage_coefficient_k',
                'ordering': ['famille', 'localite'],
            },
        ),
        migrations.CreateModel(
            name='PlagePrixFamille',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('famille', models.CharField(max_length=120)),
                ('unite', models.CharField(blank=True, default='', max_length=20)),
                ('localite', models.CharField(blank=True, default='', max_length=120)),
                ('prix_min', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('prix_median', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('prix_max', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('millesime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plage de prix par famille',
                'verbose_name_plural': 'Plages de prix par famille',
                'db_table': 'economie_plage_prix_famille',
                'ordering': ['famille', 'unite', 'localite'],
            },
        ),
        migrations.CreateModel(
            name='RegleControlePrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('type_controle', models.CharField(choices=[('arithmetique', 'Arithmétique'), ('metier', 'Métier'), ('statistique', 'Statistique'), ('documentaire', 'Documentaire'), ('coherence_croisee', 'Cohérence croisée')], max_length=30)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('alerte', 'Alerte'), ('critique', 'Critique')], default='alerte', max_length=20)),
                ('parametres', models.JSONField(blank=True, default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Règle de contrôle de prix',
                'verbose_name_plural': 'Règles de contrôle de prix',
                'db_table': 'economie_regle_controle_prix',
                'ordering': ['type_controle', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DecisionMoteurPrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_decision', models.CharField(choices=[('accepte', 'Acceptée'), ('refuse', 'Refusée'), ('modifie', 'Modifiée')], max_length=20)),
                ('proposition_initiale', models.JSONField(blank=True, default=dict)),
                ('valeur_finale', models.JSONField(blank=True, default=dict)),
                ('commentaire', models.TextField(blank=True)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('etude_prix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_moteur_prix', to='economie.etudeprix')),
                ('ligne_prix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_moteur_prix', to='economie.ligneprix')),
                ('ligne_prix_etude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_moteur_prix', to='economie.ligneprixetude')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Décision du moteur de prix',
                'verbose_name_plural': 'Décisions du moteur de prix',
                'db_table': 'economie_decision_moteur_prix',
                'ordering': ['-date_decision'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioDecompositionPrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('libelle', models.CharField(max_length=200)),
                ('famille', models.CharField(blank=True, default='', max_length=120)),
                ('coefficient_k', models.DecimalField(decimal_places=4, default=Decimal('1.4500'), max_digits=8)),
                ('ratios', models.JSONField(blank=True, default=dict)),
                ('justification', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Scénario de décomposition de prix',
                'verbose_name_plural': 'Scénarios de décomposition de prix',
                'db_table': 'economie_scenario_decomposition_prix',
                'ordering': ['famille', 'code'],
                'unique_together': {('code', 'famille')},
            },
        ),
    ]
