# Generated by Django 5.2.12 on 2026-03-27 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotheque', '0002_initial'),
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_metre', models.CharField(choices=[('avant_metre', 'Avant-métré (estimatif)'), ('metre_definitif', 'Métré définitif (descriptif)'), ('metre_contradictoire', 'Métré contradictoire'), ('metre_travaux_en_cours', 'Situation de travaux'), ('metre_decompte', 'Décompte général définitif')], default='avant_metre', max_length=40, verbose_name='Type de métré')),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('archive', 'Archivé')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metres_crees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metres', to='projets.lot', verbose_name='Lot')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metres', to='projets.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Métré',
                'verbose_name_plural': 'Métrés',
                'db_table': 'metres_metre',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='LigneMetre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ordre', models.PositiveSmallIntegerField(verbose_name="N° d'ordre")),
                ('code_article', models.CharField(blank=True, max_length=50, verbose_name='Code article')),
                ('designation', models.TextField(verbose_name="Désignation de l'ouvrage")),
                ('nature', models.CharField(choices=[('travaux', 'Travaux'), ('fourniture', 'Fourniture'), ('prestation', 'Prestation de service'), ('installation_chantier', 'Installation de chantier'), ('provision', 'Provision / réserve')], default='travaux', max_length=30, verbose_name='Nature')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité')),
                ('unite', models.CharField(max_length=20, verbose_name='Unité')),
                ('detail_calcul', models.TextField(blank=True, verbose_name='Détail du métré (longueur × largeur × hauteur…)')),
                ('prix_unitaire_ht', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Prix unitaire HT (€)')),
                ('observations', models.TextField(blank=True)),
                ('ligne_bibliotheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_metre', to='bibliotheque.ligneprixbibliotheque', verbose_name='Référence bibliothèque')),
                ('metre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='metres.metre')),
            ],
            options={
                'verbose_name': 'Ligne de métré',
                'verbose_name_plural': 'Lignes de métré',
                'db_table': 'metres_ligne',
                'ordering': ['metre', 'numero_ordre'],
                'unique_together': {('metre', 'numero_ordre')},
            },
        ),
    ]
