# Generated by Django 5.2 on 2026-04-12 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FondPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé du plan (ex: Niveau 0, Façade Sud)')),
                ('format_fichier', models.CharField(choices=[('pdf', 'PDF — plan numérique'), ('image', 'Image — JPG, PNG, TIFF'), ('dxf', 'DXF — plan vectoriel CAO')], max_length=10, verbose_name='Format')),
                ('fichier', models.FileField(upload_to='metres/fonds-plan/%Y/%m/', verbose_name='Fichier du fond de plan')),
                ('echelle', models.DecimalField(blank=True, decimal_places=6, help_text='Calculée automatiquement lors de la calibration depuis le fond de plan', max_digits=10, null=True, verbose_name='Échelle (px par mètre)')),
                ('reference_calibration', models.JSONField(blank=True, default=dict, help_text='{point_a: [x,y], point_b: [x,y], distance_metres: float}', verbose_name='Points de calibration')),
                ('numero_page', models.PositiveSmallIntegerField(default=1, verbose_name='Page du PDF')),
                ('largeur_px', models.PositiveIntegerField(blank=True, null=True)),
                ('hauteur_px', models.PositiveIntegerField(blank=True, null=True)),
                ('miniature', models.FileField(blank=True, null=True, upload_to='metres/miniatures/%Y/%m/', verbose_name='Miniature (PNG)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('metre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonds_plan', to='metres.metre', verbose_name='Métré associé')),
            ],
            options={
                'verbose_name': 'Fond de plan',
                'verbose_name_plural': 'Fonds de plan',
                'db_table': 'metres_fond_plan',
                'ordering': ['metre', 'intitule'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionCAO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de traitement'), ('en_cours', 'Extraction en cours'), ('propose', 'Propositions disponibles'), ('valide', 'Propositions validées'), ('erreur', "Erreur lors de l'extraction")], default='en_attente', max_length=20)),
                ('resultat_brut', models.JSONField(blank=True, default=dict, verbose_name='Résultat brut du service CAO')),
                ('propositions', models.JSONField(blank=True, default=list, help_text='[{designation, quantite, unite, calque, surface_m2, longueur_m}]', verbose_name='Lignes de métré proposées')),
                ('nb_calques', models.PositiveIntegerField(default=0)),
                ('nb_entites', models.PositiveIntegerField(default=0)),
                ('nb_propositions', models.PositiveIntegerField(default=0)),
                ('message_erreur', models.TextField(blank=True)),
                ('date_extraction', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('metre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions_cao', to='metres.metre')),
                ('fond_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metres.fondplan')),
            ],
            options={
                'verbose_name': 'Extraction CAO',
                'db_table': 'metres_extraction_cao',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ZoneMesure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation de la zone')),
                ('type_mesure', models.CharField(choices=[('surface', 'Surface — polygone fermé'), ('longueur', 'Longueur — polyligne'), ('comptage', 'Comptage — point / objet'), ('perimetre', "Périmètre — contour d'une zone")], max_length=20, verbose_name='Type de mesure')),
                ('points_px', models.JSONField(default=list, help_text='Liste de [x, y] en pixels sur le fond de plan', verbose_name='Points de la géométrie (px)')),
                ('deductions', models.JSONField(blank=True, default=list, help_text='Liste de zones à soustraire : [{designation, points_px, surface_m2}]', verbose_name='Déductions')),
                ('valeur_brute', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valeur brute (m², ml ou unité)')),
                ('valeur_deduction', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Total des déductions')),
                ('valeur_nette', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valeur nette (après déductions)')),
                ('unite', models.CharField(default='m²', max_length=10)),
                ('couleur', models.CharField(default='#3b82f6', max_length=7, verbose_name="Couleur d'affichage (#hex)")),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fond_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='metres.fondplan', verbose_name='Fond de plan')),
                ('ligne_metre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_mesure', to='metres.lignemetre', verbose_name='Ligne de métré associée')),
            ],
            options={
                'verbose_name': 'Zone mesurée',
                'verbose_name_plural': 'Zones mesurées',
                'db_table': 'metres_zone_mesure',
                'ordering': ['fond_plan', 'ordre'],
            },
        ),
    ]
