# Generated by Django 5.2 on 2026-04-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metres', '0002_metres_visuels_fond_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fondplan',
            name='intitule',
            field=models.CharField(blank=True, max_length=200, verbose_name='Intitulé du plan (ex: Niveau 0, Façade Sud)'),
        ),
    ]
