# Generated by Django 5.2 on 2026-04-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metres', '0005_zone_mesure_numero_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metre',
            name='type_metre',
            field=models.CharField(choices=[('avant_metre', 'Avant-métré'), ('metre_definitif', 'Métré définitif'), ('metre_contradictoire', 'Métré contradictoire')], default='avant_metre', max_length=40, verbose_name='Type de métré'),
        ),
    ]
