# Generated by Django 5.2 on 2026-04-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metres', '0006_alter_metre_type_metre'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondplan',
            name='apercu',
            field=models.FileField(blank=True, null=True, upload_to='metres/apercus/%Y/%m/', verbose_name='Aperçu rapide (PNG 800px)'),
        ),
        migrations.AlterField(
            model_name='fondplan',
            name='miniature',
            field=models.FileField(blank=True, null=True, upload_to='metres/miniatures/%Y/%m/', verbose_name='Miniature HD (PNG)'),
        ),
    ]
