# Generated by Django 5.2 on 2026-04-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metres', '0007_apercu_fond_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignemetre',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Localisation (pièce, niveau, bâtiment)'),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Localisation (pièce, niveau, bâtiment)'),
        ),
    ]
