# Generated by Django 5.2 on 2026-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metres', '0008_ajoute_localisation_ligne_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonemesure',
            name='hauteur',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Si renseignée, longueur × hauteur → surface en m²', max_digits=8, null=True, verbose_name='Hauteur (m)'),
        ),
    ]
