# Generated by Django 5.2 on 2026-05-01 19:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def initialiser_statuts_compatibilite(apps, schema_editor):
    FondPlan = apps.get_model('metres', 'FondPlan')
    LigneMetre = apps.get_model('metres', 'LigneMetre')

    FondPlan.objects.filter(echelle__isnull=False).update(statut_calibration='calibre')
    FondPlan.objects.filter(echelle__isnull=True).update(statut_calibration='non_calibre')
    LigneMetre.objects.filter(ligne_bibliotheque__isnull=False).update(designation_source='importee', source_type='import')


class Migration(migrations.Migration):

    dependencies = [
        ('metres', '0009_ajoute_hauteur_zone_mesure'),
        ('pieces_ecrites', '0012_articlecctp_statut'),
        ('projets', '0012_affectationprojet_assignee_automatiquement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fondplan',
            name='echelle_x',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fondplan',
            name='echelle_y',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fondplan',
            name='message_traitement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fondplan',
            name='message_vectorisation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fondplan',
            name='page_pdf_total',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fondplan',
            name='rotation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fondplan',
            name='statut_calibration',
            field=models.CharField(choices=[('non_calibre', 'Non calibré'), ('calibre', 'Calibré'), ('calibration_a_verifier', 'Calibration à vérifier')], default='non_calibre', max_length=30),
        ),
        migrations.AddField(
            model_name='fondplan',
            name='statut_traitement',
            field=models.CharField(choices=[('televerse', 'Téléversé'), ('rendu_en_cours', 'Rendu en cours'), ('pret', 'Prêt'), ('erreur', 'Erreur')], default='televerse', max_length=30),
        ),
        migrations.AddField(
            model_name='fondplan',
            name='statut_vectorisation',
            field=models.CharField(choices=[('non_vectorise', 'Non vectorisé'), ('en_cours', 'En cours'), ('vectorise', 'Vectorisé'), ('erreur', 'Erreur')], default='non_vectorise', max_length=30),
        ),
        migrations.AddField(
            model_name='fondplan',
            name='transformation_coordonnees',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fondplan',
            name='unite_plan',
            field=models.CharField(blank=True, default='m', max_length=20),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='article_a_completer',
            field=models.BooleanField(default=False, verbose_name='Article CCTP à compléter'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='article_cctp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_metre', to='pieces_ecrites.articlecctp', verbose_name='Article CCTP lié'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='article_cctp_code',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Code article CCTP'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='article_cctp_libelle',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Libellé article CCTP'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='batiment_zone',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Bâtiment / zone'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='chapitre_cctp',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Chapitre CCTP'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='date_derniere_synchronisation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='designation_source',
            field=models.CharField(choices=[('cctp', 'Article CCTP'), ('libre', 'Désignation libre'), ('importee', 'Importée'), ('zone_visuelle', 'Zone visuelle')], default='libre', max_length=20, verbose_name='Source de désignation'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='inclure_dpgf',
            field=models.BooleanField(default=True, verbose_name='Inclure dans la DPGF'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='lot_cctp',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lot CCTP'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='niveau',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='ordre_dpgf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='piece',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Pièce'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='quantite_modifiee_manuellement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='source_fond_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_metre_sources', to='metres.fondplan', verbose_name='Fond de plan source'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='source_type',
            field=models.CharField(choices=[('manuel', 'Manuel'), ('formule', 'Formule'), ('zone_visuelle', 'Zone visuelle'), ('extraction_vectorielle', 'Extraction vectorielle'), ('import', 'Import')], default='manuel', max_length=30, verbose_name='Source de la ligne'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='source_zone_mesure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_metre_sources', to='metres.zonemesure', verbose_name='Zone mesurée source'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='statut_ligne',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('calculee', 'Calculée'), ('verifiee', 'Vérifiée'), ('validee', 'Validée'), ('integree_dpgf', 'Intégrée DPGF')], default='brouillon', max_length=20, verbose_name='Statut de ligne'),
        ),
        migrations.AddField(
            model_name='lignemetre',
            name='statut_synchronisation',
            field=models.CharField(choices=[('manuel', 'Manuel'), ('synchronisee', 'Synchronisée'), ('desynchronisee', 'Désynchronisée')], default='manuel', max_length=20, verbose_name='Synchronisation zone'),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='article_cctp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_mesure', to='pieces_ecrites.articlecctp', verbose_name='Article CCTP lié'),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='chapitre_cctp',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='code_article',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='date_dernier_calcul',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='date_derniere_conversion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='geometrie_modifiee_depuis_conversion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='localisation_structuree',
            field=models.JSONField(blank=True, default=dict, verbose_name='Localisation structurée'),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='lot_cctp',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='message_erreur_calcul',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='source_article_cctp',
            field=models.CharField(choices=[('cctp', 'Article CCTP'), ('libre', 'Désignation libre'), ('importee', 'Importée'), ('zone_visuelle', 'Zone visuelle')], default='zone_visuelle', max_length=20),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='statut_calcul',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('calculee', 'Calculée'), ('erreur', 'Erreur')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='statut_conversion',
            field=models.CharField(choices=[('non_convertie', 'Non convertie'), ('convertie', 'Convertie'), ('desynchronisee', 'Désynchronisée'), ('synchronisee', 'Synchronisée')], default='non_convertie', max_length=20),
        ),
        migrations.AddField(
            model_name='zonemesure',
            name='statut_synchronisation',
            field=models.CharField(choices=[('non_convertie', 'Non convertie'), ('convertie', 'Convertie'), ('desynchronisee', 'Désynchronisée'), ('synchronisee', 'Synchronisée')], default='non_convertie', max_length=20),
        ),
        migrations.CreateModel(
            name='DPGFQuantitative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=300)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('generee', 'Générée'), ('transmise_economie', "Transmise à l'économie"), ('archivee', 'Archivée')], default='generee', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('metre_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dpgf_quantitatives', to='metres.metre')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpgf_quantitatives', to='projets.projet')),
            ],
            options={
                'verbose_name': 'DPGF quantitative',
                'verbose_name_plural': 'DPGF quantitatives',
                'db_table': 'metres_dpgf_quantitative',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='GeometrieFondPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.PositiveSmallIntegerField(default=1)),
                ('type_source', models.CharField(choices=[('dxf', 'DXF/DWG'), ('pdf_vectoriel', 'PDF vectoriel'), ('raster_vectorise', 'Raster vectorisé')], max_length=30)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('disponible', 'Disponible'), ('erreur', 'Erreur')], default='en_attente', max_length=20)),
                ('donnees_geojson', models.JSONField(blank=True, default=dict)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('contours', models.JSONField(blank=True, default=list)),
                ('points_accroche', models.JSONField(blank=True, default=list)),
                ('calques', models.JSONField(blank=True, default=list)),
                ('statistiques', models.JSONField(blank=True, default=dict)),
                ('message_erreur', models.TextField(blank=True, default='')),
                ('date_generation', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fond_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='metres.fondplan')),
            ],
            options={
                'verbose_name': 'Géométrie de fond de plan',
                'verbose_name_plural': 'Géométries de fonds de plan',
                'db_table': 'metres_geometrie_fond_plan',
                'ordering': ['fond_plan', 'page', '-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='LigneDPGFQuantitative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot', models.CharField(blank=True, default='', max_length=200)),
                ('chapitre', models.CharField(blank=True, default='', max_length=200)),
                ('code_article', models.CharField(blank=True, default='', max_length=80)),
                ('designation', models.TextField()),
                ('localisation', models.CharField(blank=True, default='', max_length=240)),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('unite', models.CharField(blank=True, default='', max_length=30)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('observations', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('a_completer', 'À compléter')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('article_cctp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_dpgf_quantitative', to='pieces_ecrites.articlecctp')),
                ('dpgf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='metres.dpgfquantitative')),
                ('ligne_metre_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_dpgf_quantitative', to='metres.lignemetre')),
                ('zone_mesure_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_dpgf_quantitative', to='metres.zonemesure')),
            ],
            options={
                'verbose_name': 'Ligne DPGF quantitative',
                'verbose_name_plural': 'Lignes DPGF quantitatives',
                'db_table': 'metres_ligne_dpgf_quantitative',
                'ordering': ['dpgf', 'ordre'],
            },
        ),
        migrations.RunPython(initialiser_statuts_compatibilite, migrations.RunPython.noop),
    ]
