# Generated by Django 5.2.12 on 2026-03-27 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalProgramme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('categorie', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('nombre', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre')),
                ('surface_unitaire_m2', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Surface unitaire (m²)')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locaux',
                'db_table': 'batiment_local',
                'ordering': ['programme', 'categorie', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeBatiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé du programme')),
                ('type_operation', models.CharField(choices=[('construction_neuve', 'Construction neuve'), ('rehabilitation', 'Réhabilitation'), ('extension', 'Extension'), ('renovation_lourde', 'Rénovation lourde'), ('demolition_reconstruction', 'Démolition-reconstruction')], default='construction_neuve', max_length=30, verbose_name="Type d'opération")),
                ('type_batiment', models.CharField(choices=[('logement_collectif', 'Logement collectif'), ('logement_individuel', 'Logement individuel'), ('bureaux', 'Bureaux'), ('commerce', 'Commerce'), ('enseignement', 'Enseignement'), ('sante', 'Santé'), ('sport_loisirs', 'Sport et loisirs'), ('industrie_logistique', 'Industrie / logistique'), ('autre', 'Autre')], default='logement_collectif', max_length=30, verbose_name='Type de bâtiment')),
                ('shon_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SHON totale (m²)')),
                ('shab_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface habitable totale (m²)')),
                ('emprise_sol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Emprise au sol (m²)')),
                ('nombre_niveaux_hors_sol', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de niveaux hors sol')),
                ('nombre_niveaux_sous_sol', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de niveaux sous sol')),
                ('cout_estime_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Coût estimé global HT (€)')),
                ('cout_par_m2_shon_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût / m² SHON HT (€)')),
                ('indice_base', models.CharField(blank=True, max_length=20, verbose_name='Indice BT de base (ex : BT01)')),
                ('date_valeur', models.DateField(blank=True, null=True, verbose_name="Date de valeur de l'estimation")),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programme bâtiment',
                'verbose_name_plural': 'Programmes bâtiment',
                'db_table': 'batiment_programme',
                'ordering': ['-date_modification'],
            },
        ),
    ]
