# Generated by Django 5.2.12 on 2026-03-27 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batiment', '0001_initial'),
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmebatiment',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes_batiment', to='projets.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='localprogramme',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaux', to='batiment.programmebatiment', verbose_name='Programme'),
        ),
    ]
