# Generated by Django 5.2 on 2026-04-14 00:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotheque', '0009_ajout_illustrations_ligne_prix'),
        ('pieces_ecrites', '0010_articlecctp_lot_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevisAnalyse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='ressources/devis/%Y/%m/', verbose_name='Fichier')),
                ('nom_original', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('type_document', models.CharField(choices=[('devis', 'Devis'), ('dqe', 'DQE'), ('bpu', 'BPU'), ('dpgf', 'DPGF'), ('bon_commande', 'Bon de commande'), ('autre', 'Autre')], default='devis', max_length=50, verbose_name='Type de document')),
                ('entreprise', models.CharField(blank=True, max_length=200, verbose_name='Entreprise émettrice')),
                ('localite', models.CharField(blank=True, max_length=200, verbose_name='Localité / Zone géographique')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('indice_base_code', models.CharField(default='BT01', max_length=10, verbose_name='Indice de base')),
                ('indice_base_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Valeur de l'indice à la date d'émission")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'Analyse en cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('erreur_detail', models.TextField(blank=True, verbose_name="Détail de l'erreur")),
                ('date_suppression_programmee', models.DateField(blank=True, help_text='Laisser vide pour conserver indéfiniment.', null=True, verbose_name='Suppression programmée le')),
                ('capitalise', models.BooleanField(default=False, verbose_name='Capitalisé en bibliothèque')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Devis analysé',
                'verbose_name_plural': 'Devis analysés',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EstimationSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='ressources/estimations/%Y/%m/', verbose_name='Fichier')),
                ('nom_original', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('type_document', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image (JPG/PNG)'), ('archive', 'Archive (ZIP/RAR)'), ('tableur', 'Tableur (XLSX/ODS)'), ('autre', 'Autre')], default='pdf', max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'Analyse en cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('erreur_detail', models.TextField(blank=True)),
                ('date_suppression_programmee', models.DateField(blank=True, null=True, verbose_name='Suppression programmée le')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Source d'estimation",
                'verbose_name_plural': "Sources d'estimation",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='FicheRatioCout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé du projet')),
                ('type_projet', models.CharField(choices=[('logement_collectif', 'Logement collectif'), ('logement_individuel', 'Logement individuel'), ('bureaux', 'Bureaux'), ('equipement_scolaire', 'Équipement scolaire'), ('equipement_sportif', 'Équipement sportif'), ('equipement_culturel', 'Équipement culturel'), ('commerce', 'Commerce / Retail'), ('industrie', 'Industrie / Entrepôt'), ('sante', 'Santé / ERP'), ('vrd_amenagements', 'VRD / Aménagements extérieurs'), ('autre', 'Autre')], default='logement_collectif', max_length=50, verbose_name='Type de projet')),
                ('localite', models.CharField(blank=True, max_length=200, verbose_name='Localité')),
                ('annee_reference', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de référence')),
                ('shon', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SHON (m²)')),
                ('shab', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SHAB (m²)')),
                ('emprise_sol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Emprise au sol (m²)')),
                ('nombre_niveaux_hors_sol', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Niveaux hors sol')),
                ('nombre_niveaux_sous_sol', models.PositiveSmallIntegerField(default=0, verbose_name='Niveaux en sous-sol')),
                ('type_fondation', models.CharField(choices=[('superficielle_semelle', 'Semelles superficielles'), ('superficielle_radier', 'Radier général'), ('profonde_pieux_beton', 'Pieux béton forés'), ('profonde_pieux_metalliques', 'Pieux métalliques'), ('profonde_micropieux', 'Micropieux'), ('profonde_paroi_moulee', 'Paroi moulée'), ('non_identifie', 'Non identifié')], default='non_identifie', max_length=50, verbose_name='Type de fondation')),
                ('profondeur_fondation_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Profondeur de fondation (m)')),
                ('nature_sol', models.CharField(blank=True, max_length=200, verbose_name='Nature du sol')),
                ('cout_total_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Coût total HT (€)')),
                ('cout_infrastructure_ht', models.DecimalField(blank=True, decimal_places=2, help_text='Fondations, terrassements, réseaux sous-dallage', max_digits=14, null=True, verbose_name='Coût infrastructure HT (€)')),
                ('cout_superstructure_ht', models.DecimalField(blank=True, decimal_places=2, help_text='Structure bâtie hors fondations', max_digits=14, null=True, verbose_name='Coût superstructure HT (€)')),
                ('cout_m2_shon', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût/m² SHON (€/m²)')),
                ('cout_m2_shab', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût/m² SHAB (€/m²)')),
                ('cout_m2_emprise', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût/m² emprise (€/m²)')),
                ('ratio_infra_pct', models.DecimalField(blank=True, decimal_places=2, help_text="% du coût total imputé à l'infrastructure", max_digits=5, null=True, verbose_name='Part infrastructure (%)')),
                ('ratio_supra_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Part superstructure (%)')),
                ('indice_code', models.CharField(default='BT01', max_length=10, verbose_name='Indice de référence')),
                ('indice_valeur_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Valeur de l'indice à la date de référence")),
                ('reference_externe', models.CharField(blank=True, max_length=300, verbose_name='Référence externe')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('lots_cctp', models.ManyToManyField(blank=True, related_name='fiches_ratio', to='pieces_ecrites.lotcctp', verbose_name="Corps d'état concernés")),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_ratio', to='ressources.estimationsource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Fiche ratio de coût',
                'verbose_name_plural': 'Fiches ratio de coût',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='IndiceRevisionPrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('BT01', 'BT01 — Gros œuvre / Bâtiment général'), ('BT02', 'BT02 — Maçonnerie'), ('BT10', 'BT10 — Charpente bois'), ('BT20', 'BT20 — Couverture'), ('BT28', 'BT28 — Peinture'), ('BT37', 'BT37 — Menuiserie bois'), ('BT40', 'BT40 — Serrurerie'), ('BT50', 'BT50 — Plomberie'), ('BT51', 'BT51 — CVC / Chauffage'), ('BT60', 'BT60 — Électricité'), ('TP01', 'TP01 — Terrassements'), ('TP05', 'TP05 — Canalisations'), ('TP09', 'TP09 — Béton hydraulique')], max_length=10, verbose_name='Code indice')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valeur')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('source', models.CharField(default='INSEE', max_length=200, verbose_name='Source')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Indice de révision des prix',
                'verbose_name_plural': 'Indices de révision des prix',
                'ordering': ['-date_publication', 'code'],
                'unique_together': {('code', 'date_publication')},
            },
        ),
        migrations.CreateModel(
            name='LignePrixMarche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=500, verbose_name='Désignation')),
                ('designation_normalisee', models.CharField(blank=True, help_text='Version nettoyée pour la détection de similarité.', max_length=500, verbose_name='Désignation normalisée')),
                ('unite', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('prix_ht_original', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Prix HT original (€)')),
                ('prix_ht_actualise', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Prix HT actualisé (€)')),
                ('date_indice_actualisation', models.DateField(blank=True, null=True, verbose_name="Date d'actualisation")),
                ('indice_code', models.CharField(default='BT01', max_length=10, verbose_name='Indice utilisé')),
                ('indice_valeur_base', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valeur indice à la date du devis')),
                ('indice_valeur_actuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valeur indice actuelle')),
                ('localite', models.CharField(blank=True, max_length=200, verbose_name='Localité')),
                ('corps_etat', models.CharField(blank=True, max_length=20, verbose_name="Corps d'état (code lot)")),
                ('corps_etat_libelle', models.CharField(blank=True, max_length=200, verbose_name="Corps d'état (libellé)")),
                ('debourse_sec_estime', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Déboursé sec estimé (€)')),
                ('kpv_estime', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Kpv estimé')),
                ('pct_mo_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% MO estimé')),
                ('pct_materiaux_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Matériaux estimé')),
                ('pct_materiel_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Matériel estimé')),
                ('est_ligne_commune', models.BooleanField(default=False, verbose_name='Ligne commune (fusion de similaires)')),
                ('nb_occurrences', models.PositiveIntegerField(default=1, verbose_name="Nombre d'occurrences fusionnées")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('devis_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes', to='ressources.devisanalyse', verbose_name='Devis source')),
                ('ligne_bibliotheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prix_marche', to='bibliotheque.ligneprixbibliotheque', verbose_name='Ligne bibliothèque liée')),
            ],
            options={
                'verbose_name': 'Ligne de prix marché',
                'verbose_name_plural': 'Lignes de prix marché',
                'ordering': ['-date_creation'],
            },
        ),
    ]
