# Generated by Django 5.2 on 2026-04-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicerevisionprix',
            name='code',
            field=models.CharField(choices=[('BTM', 'BTM — Bâtiment Tous Métiers (agrégé)'), ('TPM', 'TPM — Travaux Publics Tous Métiers (agrégé)'), ('BT01', 'BT01 — Gros œuvre / Bâtiment général'), ('BT02', 'BT02 — Maçonnerie'), ('BT10', 'BT10 — Charpente bois'), ('BT20', 'BT20 — Couverture'), ('BT28', 'BT28 — Peinture'), ('BT37', 'BT37 — Menuiserie bois'), ('BT40', 'BT40 — Serrurerie'), ('BT50', 'BT50 — Plomberie'), ('BT51', 'BT51 — CVC / Chauffage'), ('BT60', 'BT60 — Électricité'), ('TP01', 'TP01 — Terrassements'), ('TP05', 'TP05 — Canalisations'), ('TP09', 'TP09 — Béton hydraulique')], max_length=10, verbose_name='Code indice'),
        ),
    ]
