# Generated by Django 5.2 on 2026-04-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0002_alter_indicerevisionprix_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicerevisionprix',
            name='code',
            field=models.CharField(choices=[('BTM', 'BTM — Bâtiment Mayotte'), ('TPM', 'TPM — Travaux Publics Mayotte'), ('BT01', "BT01 — Tous corps d'état"), ('BT02', 'BT02 — Terrassements'), ('BT03', 'BT03 — Maçonnerie et canalisations béton'), ('BT06', 'BT06 — Ossature, ouvrages en béton armé'), ('BT07', 'BT07 — Ossature et charpentes métalliques'), ('BT08', 'BT08 — Plâtre et préfabriqués'), ('BT09', 'BT09 — Carrelage et revêtement céramique'), ('BT10', 'BT10 — Revêtements plastiques'), ('BT16b', 'BT16b — Charpente bois'), ('BT18a', 'BT18a — Menuiserie intérieure bois'), ('BT19b', 'BT19b — Menuiserie extérieure bois'), ('BT26', 'BT26 — Fermeture de baies en plastique / PVC'), ('BT27', 'BT27 — Fermeture de baies en aluminium'), ('BT28', 'BT28 — Fermeture de baies en métal ferreux'), ('BT30', 'BT30 — Couverture en ardoises'), ('BT32', 'BT32 — Couverture en tuiles terre cuite'), ('BT34', 'BT34 — Couverture en zinc et métal'), ('BT38', 'BT38 — Plomberie sanitaire'), ('BT40', 'BT40 — Chauffage central'), ('BT41', "BT41 — Ventilation et conditionnement d'air"), ('BT47', 'BT47 — Électricité'), ('BT50', "BT50 — Rénovation, entretien tous corps d'état"), ('BT51', 'BT51 — Menuiseries PVC'), ('TP01', 'TP01 — Index général tous travaux'), ('TP02', "TP02 — Génie civil et ouvrages d'art"), ('TP03a', 'TP03a — Grands terrassements'), ('TP04', 'TP04 — Fondations et travaux géotechniques'), ('TP05a', 'TP05a — Travaux souterrains traditionnels'), ('TP08', 'TP08 — Voirie rurale et urbaine'), ('TP09', "TP09 — Fabrication et mise en œuvre d'enrobés"), ('TP10b', 'TP10b — Canalisations sans fourniture de tuyaux')], max_length=10, verbose_name='Code indice'),
        ),
    ]
