# Generated by Django 5.2 on 2026-05-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_alter_indicerevisionprix_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='devisanalyse',
            name='donnees_extraction',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='devisanalyse',
            name='message_analyse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devisanalyse',
            name='methode_extraction',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='devisanalyse',
            name='nb_lignes_a_verifier',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devisanalyse',
            name='nb_lignes_detectees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devisanalyse',
            name='nb_lignes_rejetees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devisanalyse',
            name='score_qualite_extraction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='devisanalyse',
            name='texte_extrait_apercu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='corrections_proposees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='decision_import',
            field=models.CharField(choices=[('a_decider', 'À décider'), ('importer', 'Importer'), ('ignorer', 'Ignorer'), ('fusionner', 'Fusionner'), ('mettre_a_jour', 'Mettre à jour')], default='a_decider', max_length=30),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='designation_originale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='donnees_import',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='ecart_montant_ht',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='montant_ht',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='montant_recalcule_ht',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='numero',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='quantite',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='score_confiance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='statut_controle',
            field=models.CharField(choices=[('ok', 'OK'), ('alerte', 'Alerte'), ('erreur', 'Erreur'), ('ignoree', 'Ignorée'), ('corrigee', 'Corrigée')], default='ok', max_length=30),
        ),
        migrations.AddField(
            model_name='ligneprixmarche',
            name='type_ligne',
            field=models.CharField(choices=[('article', 'Article'), ('titre', 'Titre'), ('sous_total', 'Sous-total'), ('total', 'Total'), ('commentaire', 'Commentaire')], default='article', max_length=30),
        ),
        migrations.AlterField(
            model_name='devisanalyse',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'Analyse en cours'), ('termine', 'Terminé'), ('a_verifier', 'À vérifier'), ('erreur', 'Erreur')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
