# Generated by Django 5.2 on 2026-05-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0004_devisanalyse_donnees_extraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneprixmarche',
            name='designation',
            field=models.TextField(verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='ligneprixmarche',
            name='designation_normalisee',
            field=models.TextField(blank=True, help_text='Version nettoyée pour la détection de similarité.', verbose_name='Désignation normalisée'),
        ),
    ]
