# Generated by Django 5.2 on 2026-05-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0005_alter_ligneprixmarche_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneprixmarche',
            name='type_ligne',
            field=models.CharField(choices=[('article', 'Article'), ('titre', 'Titre'), ('chapitre', 'Chapitre'), ('sous_chapitre', 'Sous-chapitre'), ('entete_tableau', 'Entête tableau'), ('sous_total', 'Sous-total'), ('total', 'Total'), ('total_general', 'Total général'), ('commentaire', 'Commentaire'), ('ligne_vide', 'Ligne vide'), ('ligne_pointilles', 'Ligne de pointillés'), ('ligne_a_verifier', 'Ligne à vérifier'), ('ignoree', 'Ignorée')], default='article', max_length=30),
        ),
    ]
