# Generated by Django 5.2 on 2026-05-02 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0006_alter_ligneprixmarche_type_ligne'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleMappingDocumentPrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('type_document', models.CharField(blank=True, max_length=50, verbose_name='Type de document')),
                ('entreprise_source', models.CharField(blank=True, max_length=200, verbose_name='Entreprise / source')),
                ('colonnes_mapping', models.JSONField(blank=True, default=dict, verbose_name='Colonnes mappées')),
                ('regles_nettoyage', models.JSONField(blank=True, default=dict, verbose_name='Règles de lecture')),
                ('regles_ignore', models.JSONField(blank=True, default=dict, verbose_name="Règles d'ignore")),
                ('separateur_description', models.CharField(blank=True, max_length=100, verbose_name='Séparateur description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de mapping document prix',
                'verbose_name_plural': 'Modèles de mapping document prix',
                'ordering': ['-date_modification'],
            },
        ),
    ]
