# Generated by Django 5.2.12 on 2026-03-27 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('intitule', models.CharField(max_length=500, verbose_name='Intitulé')),
                ('type_projet', models.CharField(choices=[('etude', 'Étude'), ('travaux', 'Travaux'), ('mission_moe', "Mission maîtrise d'œuvre"), ('assistance', "Assistance à maîtrise d'ouvrage"), ('expertise', 'Expertise'), ('autre', 'Autre')], default='etude', max_length=50, verbose_name='Type')),
                ('statut', models.CharField(choices=[('prospection', 'Prospection'), ('en_cours', 'En cours'), ('suspendu', 'Suspendu'), ('termine', 'Terminé'), ('abandonne', 'Abandonné'), ('archive', 'Archivé')], default='en_cours', max_length=30, verbose_name='Statut')),
                ('phase_actuelle', models.CharField(blank=True, choices=[('faisabilite', 'Faisabilité'), ('programmation', 'Programmation'), ('esquisse', 'Esquisse / ESQ'), ('avp', 'Avant-projet sommaire / APS'), ('pro', 'Avant-projet définitif / APD / PRO'), ('dce', 'Dossier de consultation / DCE'), ('ao', "Appel d'offres"), ('exe', 'Exécution / DET'), ('reception', 'Réception / AOR'), ('clos', 'Clos')], max_length=30, verbose_name='Phase actuelle')),
                ('commune', models.CharField(blank=True, max_length=200, verbose_name='Commune')),
                ('departement', models.CharField(blank=True, max_length=3, verbose_name='Département')),
                ('date_debut_prevue', models.DateField(blank=True, null=True, verbose_name='Début prévu')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Fin prévue')),
                ('date_debut_reelle', models.DateField(blank=True, null=True, verbose_name='Début réel')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Fin réelle')),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant estimé HT (€)')),
                ('montant_marche', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant du marché HT (€)')),
                ('honoraires_prevus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Honoraires prévus HT (€)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('publier_sur_site', models.BooleanField(default=False, verbose_name='Publier sur le site vitrine')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projets_crees', to=settings.AUTH_USER_MODEL)),
                ('maitre_oeuvre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projets_en_tant_que_moe', to='organisations.organisation', verbose_name="Maître d'œuvre")),
                ('maitre_ouvrage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projets_en_tant_que_mo', to='organisations.organisation', verbose_name="Maître d'ouvrage")),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='organisations.organisation', verbose_name="Bureau d'études")),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'db_table': 'projets_projet',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Numéro de lot')),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True)),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table': 'projets_lot',
                'ordering': ['projet', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('responsable', 'Responsable'), ('charge_affaires', "Chargé d'affaires"), ('economiste', 'Économiste'), ('redacteur', 'Rédacteur'), ('verificateur', 'Vérificateur'), ('conducteur_travaux', 'Conducteur de travaux'), ('observateur', 'Observateur')], default='economiste', max_length=50)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenants', to='projets.projet')),
            ],
            options={
                'verbose_name': 'Intervenant',
                'db_table': 'projets_intervenant',
            },
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['statut'], name='projets_pro_statut_2c59ef_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['organisation'], name='projets_pro_organis_b017fa_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['reference'], name='projets_pro_referen_d06ee0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('projet', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='intervenant',
            unique_together={('projet', 'utilisateur')},
        ),
    ]
