# Generated by Django 5.2 on 2026-04-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="type_projet_autre",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="Type de projet personnalisé",
            ),
        ),
    ]
