# Generated by Django 5.2.12 on 2026-04-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_projet_type_projet_autre'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='clientele_cible',
            field=models.CharField(choices=[('moa_publique', "Maîtrise d'ouvrage publique"), ('moe_conception', "Équipe de maîtrise d'œuvre"), ('entreprise_travaux', 'Entreprise de travaux'), ('cotraitrance', 'Co-traitance'), ('sous_traitance', 'Sous-traitance'), ('autre', 'Autre contexte')], default='moa_publique', max_length=30, verbose_name='Clientèle cible'),
        ),
        migrations.AddField(
            model_name='projet',
            name='objectif_mission',
            field=models.CharField(choices=[('verifier_enveloppe', "Vérifier l'enveloppe budgétaire"), ('estimation_moe', "Estimation analytique de maîtrise d'œuvre"), ('redaction_dce_cctp', 'Rédaction DCE / CCTP'), ('reponse_ao_entreprise', "Réponse à appel d'offres entreprise"), ('devis_entreprise', 'Chiffrage de devis / BPU / DPGF'), ('prospection_ao', "Prospection et sélection d'appels d'offres"), ('suivi_execution', "Suivi d'exécution et bilan"), ('autre', 'Autre objectif')], default='verifier_enveloppe', max_length=40, verbose_name='Objectif principal de la mission'),
        ),
    ]
