# Generated by Django 5.2 on 2026-04-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_projet_clientele_cible_projet_objectif_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='qualification_wizard',
            field=models.JSONField(blank=True, default=dict, verbose_name='Qualification métier du projet'),
        ),
    ]
