# Generated by Django 5.2 on 2026-04-19 01:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_prealyses_sources_et_organisation_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('famille_client', models.CharField(choices=[('maitrise_ouvrage', "Maîtrise d'ouvrage"), ('maitrise_oeuvre', "Maîtrise d'œuvre"), ('entreprise', 'Entreprise'), ('autre', 'Autre contexte')], max_length=30, verbose_name='Famille client')),
                ('sous_types_client', models.JSONField(blank=True, default=list, help_text='Liste de codes sous-types applicables (vide = tous)', verbose_name='Sous-types clients')),
                ('nature_ouvrage', models.CharField(choices=[('batiment', 'Bâtiment'), ('infrastructure', 'Infrastructure / VRD'), ('mixte', 'Mixte'), ('tous', 'Tous types')], default='tous', max_length=20, verbose_name="Nature d'ouvrage")),
                ('phases_concernees', models.JSONField(blank=True, default=list, help_text='Codes des phases : esq, aps, apd, pro, act, exe, det, opc, aor', verbose_name='Phases MOP concernées')),
                ('icone', models.CharField(blank=True, help_text="Nom d'icône Lucide (ex: FileText, Calculator)", max_length=60, verbose_name='Icône')),
                ('couleur', models.CharField(blank=True, help_text='Couleur Tailwind (ex: blue, green, amber)', max_length=20, verbose_name='Couleur')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('est_obligatoire', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mission client',
                'verbose_name_plural': 'Missions clients',
                'db_table': 'projets_mission_client',
                'ordering': ['famille_client', 'ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('type_modele', models.CharField(choices=[('cctp', 'CCTP'), ('dpgf', 'DPGF'), ('bpu', 'BPU / DQE'), ('os', 'Ordre de service'), ('decompte', 'Décompte / DGD'), ('avenant', 'Avenant'), ('rapport_analyse', "Rapport d'analyse des offres"), ('cr_chantier', 'Compte-rendu de chantier'), ('contrat', 'Contrat / marché'), ('memoire_technique', 'Mémoire technique'), ('note_estimation', "Note d'estimation budgétaire"), ('planning', 'Planning prévisionnel'), ('autre', 'Autre')], max_length=30, verbose_name='Type de modèle')),
                ('format_sortie', models.CharField(choices=[('docx', 'Word (.docx)'), ('xlsx', 'Excel (.xlsx)'), ('odt', 'Writer (.odt)'), ('ods', 'Calc (.ods)')], default='docx', max_length=10, verbose_name='Format de sortie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('familles_client', models.JSONField(blank=True, default=list, help_text='Familles client pour lesquelles ce modèle est disponible (vide = toutes)', verbose_name='Familles client')),
                ('variables_parametrables', models.JSONField(blank=True, default=list, help_text='Ex: [{"code": "nom_projet", "libelle": "Nom du projet", "type": "texte", "obligatoire": true}]', verbose_name='Variables paramétrables')),
                ('template_fichier', models.FileField(blank=True, help_text='Fichier source (.docx, .xlsx, .odt, .ods) utilisé pour la génération', null=True, upload_to='modeles-documents/', verbose_name='Fichier modèle')),
                ('apercu_image', models.ImageField(blank=True, null=True, upload_to='modeles-documents/apercu/', verbose_name="Image d'aperçu")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
                'db_table': 'projets_modele_document',
                'ordering': ['type_modele', 'ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='LivrableType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('type_document', models.CharField(choices=[('cctp', 'CCTP'), ('dpgf', 'DPGF'), ('bpu', 'BPU'), ('dqe', 'DQE'), ('note_calcul', 'Note de calcul'), ('planning', 'Planning'), ('rapport', 'Rapport / analyse'), ('plan', 'Plan / dessin'), ('devis', 'Devis'), ('contrat', 'Contrat / marché'), ('pv_reception', 'PV de réception'), ('dce', 'DCE complet'), ('memoire_technique', 'Mémoire technique'), ('dgd', 'DGD'), ('avenant', 'Avenant'), ('situation', 'Situation de travaux'), ('estimation', 'Estimation budgétaire'), ('autre', 'Autre')], max_length=30, verbose_name='Type de document')),
                ('format_attendu', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (.docx)'), ('xlsx', 'Excel (.xlsx)'), ('odt', 'Writer (.odt)'), ('ods', 'Calc (.ods)'), ('zip', 'Archive (.zip)'), ('autre', 'Autre')], default='pdf', max_length=10, verbose_name='Format attendu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, max_length=60, verbose_name='Icône')),
                ('couleur', models.CharField(blank=True, max_length=20, verbose_name='Couleur')),
                ('est_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('missions', models.ManyToManyField(blank=True, related_name='livrables', to='projets.missionclient', verbose_name='Missions associées')),
            ],
            options={
                'verbose_name': 'Livrable type',
                'verbose_name_plural': 'Livrables types',
                'db_table': 'projets_livrable_type',
                'ordering': ['ordre', 'libelle'],
            },
        ),
    ]
