# Generated by Django 5.2 on 2026-04-26 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0008_affectationprojet'),
        ('societe', '0009_parametresociete_decomposition_heures_productives'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionclient',
            name='duree_etude_heures',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=7, verbose_name="Durée d'étude par défaut"),
        ),
        migrations.AddField(
            model_name='missionclient',
            name='profil_horaire_defaut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_client_defaut', to='societe.profilhoraire', verbose_name='Profil horaire par défaut'),
        ),
    ]
