# Generated by Django 5.2 on 2026-04-26 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0009_mission_client_chiffrage_defaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningGeneral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.CharField(default='Planning général', max_length=300, verbose_name='Intitulé')),
                ('mode', models.CharField(choices=[('general', 'Planning général'), ('execution', "Planning d'exécution")], default='general', max_length=20, verbose_name='Mode')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings_generaux', to='projets.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Planning général',
                'verbose_name_plural': 'Plannings généraux',
                'db_table': 'projets_planning_general',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='TacheGantt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_tache', models.CharField(choices=[('lot', 'Lot'), ('article', 'Article DPGF'), ('tache', 'Tâche libre'), ('jalon', 'Jalon')], default='tache', max_length=20, verbose_name='Type')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code')),
                ('intitule', models.CharField(max_length=500, verbose_name='Intitulé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('progression', models.PositiveSmallIntegerField(default=0, verbose_name='Avancement (%)')),
                ('dependances', models.JSONField(blank=True, default=list, verbose_name='Dépendances (IDs)')),
                ('ressources', models.JSONField(blank=True, default=list, verbose_name='Ressources affectées')),
                ('montant_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant HT')),
                ('source_ligne_dpgf', models.UUIDField(blank=True, null=True, verbose_name='ID ligne DPGF source')),
                ('couleur', models.CharField(blank=True, max_length=20, verbose_name='Couleur')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projets.planninggeneral', verbose_name='Planning')),
                ('tache_parente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_taches', to='projets.tachegantt', verbose_name='Tâche parente')),
            ],
            options={
                'verbose_name': 'Tâche Gantt',
                'verbose_name_plural': 'Tâches Gantt',
                'db_table': 'projets_tache_gantt',
                'ordering': ['planning', 'ordre'],
            },
        ),
    ]
