# Generated by Django 5.2 on 2026-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0010_ajoute_planning_general_gantt'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionclient',
            name='coefficient_complexite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Coefficient de complexité'),
        ),
        migrations.AddField(
            model_name='missionclient',
            name='complexite',
            field=models.CharField(choices=[('simple', 'Simple'), ('standard', 'Standard'), ('complexe', 'Complexe'), ('tres_complexe', 'Très complexe')], default='standard', max_length=20, verbose_name='Complexité'),
        ),
        migrations.AddField(
            model_name='missionclient',
            name='duree_etude_jours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Durée en jours par défaut'),
        ),
        migrations.AddField(
            model_name='missionclient',
            name='inclusion_recommandee_devis',
            field=models.BooleanField(default=True, verbose_name='Recommandée dans les devis'),
        ),
        migrations.AddField(
            model_name='missionclient',
            name='mode_chiffrage_defaut',
            field=models.CharField(choices=[('taux_moyen_be', 'Taux horaire moyen BE'), ('taux_profil', 'Taux horaire profil'), ('forfait_jour_profil', 'Forfait jour profil'), ('forfait_mission', 'Forfait mission')], default='taux_profil', max_length=30, verbose_name='Mode de chiffrage par défaut'),
        ),
        migrations.AddField(
            model_name='missionclient',
            name='nature_livrable',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nature de livrable'),
        ),
        migrations.AddField(
            model_name='missionclient',
            name='phase_mission',
            field=models.CharField(choices=[('ESQ', 'ESQ'), ('APS', 'APS'), ('APD', 'APD'), ('PRO', 'PRO'), ('ACT', 'ACT'), ('VISA', 'VISA'), ('DET', 'DET'), ('AOR', 'AOR'), ('OPC', 'OPC'), ('autre', 'Autre')], default='autre', max_length=10, verbose_name='Phase de mission'),
        ),
    ]
