# Generated by Django 5.2 on 2026-05-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0011_missionclient_coefficient_complexite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationprojet',
            name='assignee_automatiquement',
            field=models.BooleanField(default=False, verbose_name='Assignée automatiquement'),
        ),
        migrations.AddField(
            model_name='affectationprojet',
            name='date_assignation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'assignation"),
        ),
        migrations.AddField(
            model_name='affectationprojet',
            name='date_debut_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début prévue'),
        ),
        migrations.AddField(
            model_name='affectationprojet',
            name='date_fin_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin prévue'),
        ),
        migrations.AddField(
            model_name='affectationprojet',
            name='heures_objectif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Heures objectif'),
        ),
        migrations.AddField(
            model_name='affectationprojet',
            name='heures_restantes_estimees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Heures restantes estimées'),
        ),
        migrations.AddField(
            model_name='affectationprojet',
            name='justification_assignation',
            field=models.JSONField(blank=True, default=dict, verbose_name="Justification d'assignation"),
        ),
        migrations.AddField(
            model_name='affectationprojet',
            name='niveau_confiance_assignation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Niveau de confiance'),
        ),
        migrations.AddField(
            model_name='affectationprojet',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='affectationprojet',
            name='score_assignation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Score d'assignation"),
        ),
        migrations.AddField(
            model_name='affectationprojet',
            name='statut_charge',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('suspendue', 'Suspendue')], default='planifiee', max_length=20, verbose_name='Statut de charge'),
        ),
    ]
