# Generated by Django 5.2 on 2026-05-02 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_dossierdocumentprojet_document_dossier_and_more'),
        ('projets', '0012_affectationprojet_assignee_automatiquement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivrableProjet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100)),
                ('libelle', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('attendu', 'Attendu'), ('en_cours', 'En cours'), ('produit', 'Produit'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('abandonne', 'Abandonné')], default='attendu', max_length=20)),
                ('module_source', models.CharField(blank=True, max_length=60)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('date_production', models.DateField(blank=True, null=True)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('document_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livrables_projet', to='documents.document')),
                ('livrable_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livrables_projet', to='projets.livrabletype')),
                ('mission_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livrables_projet', to='projets.missionclient')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables_projet', to='projets.projet')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livrables_projet_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livrable projet',
                'verbose_name_plural': 'Livrables projet',
                'db_table': 'projets_livrable_projet',
                'ordering': ['ordre', 'libelle'],
                'constraints': [models.UniqueConstraint(fields=('projet', 'code'), name='projets_livrable_unique_par_projet')],
            },
        ),
    ]
