# Generated by Django 5.2.12 on 2026-03-27 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonctionnaliteActivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identifiant technique unique, ex : MODULE_VOIRIE.', max_length=100, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_active', models.BooleanField(default=True, verbose_name='Fonctionnalité active')),
                ('niveau_controle', models.CharField(choices=[('systeme', 'Système'), ('organisation', 'Organisation'), ('groupe', 'Groupe'), ('utilisateur', 'Utilisateur'), ('profil', 'Profil de droits')], default='systeme', help_text="Granularité à laquelle s'applique cette activation.", max_length=20, verbose_name='Niveau de contrôle')),
                ('modules_dependants', models.CharField(blank=True, help_text="Codes des fonctionnalités devant être actives pour que celle-ci puisse l'être. Séparer les codes par des virgules.", max_length=500, verbose_name='Modules dépendants')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonctionnalites_modifiees', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('organisation', models.ForeignKey(blank=True, help_text='Renseigner pour une activation restreinte à une organisation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonctionnalites_activables', to='organisations.organisation', verbose_name='Organisation')),
                ('profil', models.ForeignKey(blank=True, help_text='Renseigner pour une activation restreinte à un profil de droits.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonctionnalites_activables', to='comptes.profildroit', verbose_name='Profil de droits')),
                ('utilisateur', models.ForeignKey(blank=True, help_text='Renseigner pour une activation restreinte à un utilisateur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonctionnalites_activables', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Fonctionnalité activable',
                'verbose_name_plural': 'Fonctionnalités activables',
                'db_table': 'parametres_fonctionnalite_activable',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('cle', models.CharField(help_text='Identifiant technique unique, ex : ECONO_TAUX_MARGE_CIBLE.', max_length=100, unique=True, verbose_name='Clé')),
                ('valeur', models.TextField(verbose_name='Valeur courante')),
                ('type_valeur', models.CharField(choices=[('texte', 'Texte'), ('entier', 'Entier'), ('decimal', 'Décimal'), ('booleen', 'Booléen'), ('liste', 'Liste'), ('json', 'JSON')], default='texte', max_length=10, verbose_name='Type de valeur')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.CharField(help_text='Module applicatif auquel appartient ce paramètre (ex : ECONOMIE, VOIRIE).', max_length=100, verbose_name='Module')),
                ('est_verrouille', models.BooleanField(default=False, help_text='Si activé, ce paramètre ne peut être modifié que directement en base ou via un script.', verbose_name='Verrouillé')),
                ('valeur_par_defaut', models.TextField(help_text="Valeur appliquée lors d'une réinitialisation.", verbose_name='Valeur par défaut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'db_table': 'parametres_parametre',
                'ordering': ['module', 'cle'],
            },
        ),
        migrations.CreateModel(
            name='JournalModificationParametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_valeur', models.TextField(verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.TextField(verbose_name='Nouvelle valeur')),
                ('date_modification', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_parametres', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('parametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_modifications', to='parametres.parametre', verbose_name='Paramètre')),
            ],
            options={
                'verbose_name': 'Journal de modification de paramètre',
                'verbose_name_plural': 'Journal des modifications de paramètres',
                'db_table': 'parametres_journal_modification',
                'ordering': ['-date_modification'],
            },
        ),
    ]
