# Generated by Django 5.2 on 2026-05-09 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_parametres_roundcube'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationIAFonctionnelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('module', models.CharField(choices=[('ressources_devis', 'Analyse des devis / BPU / DPGF / DQE'), ('ressources_prix_marche', 'Prix marché'), ('ressources_estimations', 'Estimations & ratios'), ('bibliotheque_prix', 'Bibliothèque de prix'), ('bibliotheque_cctp', 'CCTP / pièces écrites'), ('pieces_ecrites', 'Pièces écrites')], max_length=40)),
                ('fournisseur', models.CharField(choices=[('openai', 'OpenAI'), ('autre', 'Autre fournisseur')], default='openai', max_length=30)),
                ('modele', models.CharField(blank=True, max_length=120)),
                ('modele_fallback', models.CharField(blank=True, max_length=120)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('top_p', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('max_tokens', models.PositiveIntegerField(default=2500)),
                ('prompt_systeme', models.TextField(blank=True)),
                ('prompt_controle', models.TextField(blank=True)),
                ('schema_sortie', models.JSONField(blank=True, default=dict)),
                ('seuil_confiance', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('seuil_validation_automatique', models.DecimalField(decimal_places=2, default=0.92, max_digits=5)),
                ('activer_correction_texte', models.BooleanField(default=True)),
                ('activer_normalisation', models.BooleanField(default=True)),
                ('activer_classification', models.BooleanField(default=True)),
                ('activer_rapprochement', models.BooleanField(default=True)),
                ('activer_generation', models.BooleanField(default=False)),
                ('activer_validation_auto', models.BooleanField(default=False)),
                ('validation_humaine_obligatoire', models.BooleanField(default=True)),
                ('cout_max_par_traitement', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration métier automatisée',
                'verbose_name_plural': 'Configurations métier automatisées',
                'db_table': 'parametres_configuration_ia_fonctionnelle',
                'ordering': ['module', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='TraitementIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=80)),
                ('objet_type', models.CharField(blank=True, max_length=120)),
                ('objet_id', models.CharField(blank=True, max_length=80)),
                ('statut', models.CharField(choices=[('prepare', 'Préparé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='prepare', max_length=20)),
                ('entree', models.JSONField(blank=True, default=dict)),
                ('sortie', models.JSONField(blank=True, default=dict)),
                ('score_confiance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cout_estime', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cout_reel', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('erreur', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements', to='parametres.configurationiafonctionnelle')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements_metier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de traitement métier',
                'verbose_name_plural': 'Journaux de traitements métier',
                'db_table': 'parametres_traitement_ia',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objet_type', models.CharField(max_length=120)),
                ('objet_id', models.CharField(max_length=80)),
                ('champ', models.CharField(max_length=120)),
                ('valeur_originale', models.TextField(blank=True)),
                ('valeur_proposee', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('proposee', 'Proposée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('appliquee', 'Appliquée')], default='proposee', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='parametres.traitementia')),
            ],
            options={
                'verbose_name': 'Correction métier proposée',
                'verbose_name_plural': 'Corrections métier proposées',
                'db_table': 'parametres_correction_ia',
                'ordering': ['-date_creation'],
            },
        ),
    ]
