# Generated by Django 5.2 on 2026-05-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_configurationiafonctionnelle_traitementia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationiafonctionnelle',
            name='exemple_sortie_attendue',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='configurationiafonctionnelle',
            name='mode_reel_autorise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configurationiafonctionnelle',
            name='mode_simulation_autorise',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationiafonctionnelle',
            name='options_metier',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='configurationiafonctionnelle',
            name='prompt_classification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configurationiafonctionnelle',
            name='prompt_correction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configurationiafonctionnelle',
            name='prompt_generation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configurationiafonctionnelle',
            name='prompt_normalisation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='traitementia',
            name='duree_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traitementia',
            name='mode_execution',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='traitementia',
            name='modele_utilise',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='traitementia',
            name='prompt_systeme',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='traitementia',
            name='prompt_utilisateur',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='traitementia',
            name='tokens_entree',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traitementia',
            name='tokens_sortie',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traitementia',
            name='statut',
            field=models.CharField(choices=[('prepare', 'Préparé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur'), ('simulation', 'Simulation')], default='prepare', max_length=20),
        ),
    ]
