# Generated by Django 5.2 on 2026-04-18 12:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0005_prealyses_sources_et_organisation_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilHoraire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=150, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('taux_horaire_ht', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taux horaire HT (€/h)')),
                ('couleur', models.CharField(default='#6366f1', max_length=7, verbose_name='Couleur affichage')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil horaire',
                'verbose_name_plural': 'Profils horaires',
                'db_table': 'societe_profil_horaire',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='DevisHonoraires',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='Ex : DVZ-2026-001', max_length=30, unique=True, verbose_name='Référence')),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé de la mission')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('client_nom', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_contact', models.CharField(blank=True, max_length=150, verbose_name='Interlocuteur')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('client_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('client_adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('date_validite', models.DateField(verbose_name='Date de validité')),
                ('date_acceptation', models.DateField(blank=True, null=True, verbose_name="Date d'acceptation")),
                ('date_refus', models.DateField(blank=True, null=True, verbose_name='Date de refus')),
                ('taux_tva', models.DecimalField(choices=[(Decimal('0.20'), '20 %'), (Decimal('0.10'), '10 %'), (Decimal('0.055'), '5,5 %'), (Decimal('0.00'), 'Exonéré (0 %)')], decimal_places=3, default=Decimal('0.20'), max_digits=5, verbose_name='Taux TVA')),
                ('acompte_pct', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='Acompte à la commande (%)')),
                ('delai_paiement_jours', models.PositiveSmallIntegerField(default=30, verbose_name='Délai de paiement (jours)')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('objet', models.TextField(blank=True, verbose_name='Objet / contexte de la mission')),
                ('conditions_particulieres', models.TextField(blank=True, verbose_name='Conditions particulières')),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devis_crees', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_honoraires', to='projets.projet', verbose_name='Projet lié')),
            ],
            options={
                'verbose_name': "Devis d'honoraires",
                'verbose_name_plural': "Devis d'honoraires",
                'db_table': 'societe_devis_honoraires',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='Référence')),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('en_retard', 'En retard'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('annulee', 'Annulée'), ('avoir', 'Avoir')], default='brouillon', max_length=25)),
                ('client_nom', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_contact', models.CharField(blank=True, max_length=150)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_adresse', models.TextField(blank=True)),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_relance_1', models.DateField(blank=True, null=True, verbose_name='1re relance')),
                ('date_relance_2', models.DateField(blank=True, null=True, verbose_name='2e relance')),
                ('date_relance_3', models.DateField(blank=True, null=True, verbose_name='3e relance')),
                ('taux_tva', models.DecimalField(choices=[(Decimal('0.20'), '20 %'), (Decimal('0.10'), '10 %'), (Decimal('0.055'), '5,5 %'), (Decimal('0.00'), 'Exonéré (0 %)')], decimal_places=3, default=Decimal('0.20'), max_digits=5)),
                ('penalites_retard_pct', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, verbose_name='Taux pénalités de retard (%)')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True, verbose_name='Notes / mentions légales')),
                ('notes_internes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures_creees', to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='societe.devishonoraires', verbose_name="Devis d'origine")),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='projets.projet', verbose_name='Projet lié')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'societe_facture',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('intitule', models.CharField(max_length=300, verbose_name='Désignation')),
                ('description', models.TextField(blank=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8)),
                ('unite', models.CharField(default='forfait', max_length=30)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='societe.facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'db_table': 'societe_ligne_facture',
                'ordering': ['facture', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant encaissé TTC')),
                ('mode', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('prelevement', 'Prélèvement automatique'), ('autre', 'Autre')], default='virement', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Numéro de virement, chèque, etc.', max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='societe.facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'societe_paiement',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('type_ligne', models.CharField(choices=[('horaire', 'Rémunération horaire'), ('forfait', 'Forfait'), ('frais', 'Remboursement de frais'), ('sous_traitance', 'Sous-traitance')], default='horaire', max_length=20)),
                ('phase_code', models.CharField(blank=True, max_length=30, verbose_name='Code phase')),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('nb_heures', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Nombre d'heures")),
                ('taux_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Taux horaire HT (€/h)')),
                ('montant_unitaire_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix unitaire HT')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8, verbose_name='Quantité')),
                ('unite', models.CharField(default='forfait', max_length=30, verbose_name='Unité')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Montant HT')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='societe.devishonoraires')),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='societe.profilhoraire', verbose_name='Profil intervenant')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'db_table': 'societe_ligne_devis',
                'ordering': ['devis', 'ordre'],
            },
        ),
    ]
