# Generated by Django 5.2 on 2026-04-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devishonoraires',
            name='contexte_contractuel',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Contexte contractuel'),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='contexte_projet_saisie',
            field=models.JSONField(blank=True, default=dict, verbose_name='Contexte projet préparé'),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='date_envoi_client',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi client"),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='date_expiration_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration validation client'),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='date_validation_client',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation client'),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='famille_client',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Famille client'),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='jeton_validation_client',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Jeton validation client'),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='missions_selectionnees',
            field=models.JSONField(blank=True, default=list, verbose_name='Missions et livrables vendus'),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='mode_validation',
            field=models.CharField(blank=True, choices=[('manuel', 'Validation manuelle'), ('client', 'Validation client')], default='', max_length=10, verbose_name='Mode de validation'),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='nature_marche',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Nature de marché'),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='nature_ouvrage',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name="Nature d'ouvrage"),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='role_lbh',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Rôle LBH'),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='sous_type_client',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Sous-type client'),
        ),
    ]
