# Generated by Django 5.2 on 2026-04-25 10:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("societe", "0002_devishonoraires_contexte_contractuel_and_more"),
        ("projets", "0008_affectationprojet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TempsPasse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date_saisie", models.DateField(default=django.utils.timezone.now, verbose_name="Date")),
                ("nature", models.CharField(choices=[("projet", "Projet"), ("mission", "Mission"), ("livrable", "Livrable")], default="mission", max_length=20, verbose_name="Nature")),
                ("code_cible", models.CharField(blank=True, default="", max_length=120, verbose_name="Code cible")),
                ("libelle_cible", models.CharField(blank=True, default="", max_length=255, verbose_name="Libellé cible")),
                ("nb_heures", models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Nombre d'heures")),
                ("taux_horaire", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=8, verbose_name="Taux horaire")),
                ("cout_total", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="Coût total")),
                ("commentaires", models.TextField(blank=True, verbose_name="Commentaires")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("cree_par", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="temps_passes_crees", to=settings.AUTH_USER_MODEL)),
                ("profil_horaire", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="temps_passes", to="societe.profilhoraire", verbose_name="Profil horaire")),
                ("projet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="temps_passes", to="projets.projet", verbose_name="Projet")),
                ("utilisateur", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="temps_passes", to=settings.AUTH_USER_MODEL, verbose_name="Salarié")),
            ],
            options={
                "verbose_name": "Temps passé",
                "verbose_name_plural": "Temps passés",
                "db_table": "societe_temps_passe",
                "ordering": ["-date_saisie", "-date_creation"],
            },
        ),
    ]
