# Generated by Django 5.2 on 2026-04-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("societe", "0003_tempspasse"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempspasse",
            name="statut",
            field=models.CharField(
                choices=[("brouillon", "Brouillon"), ("valide", "Validé")],
                default="brouillon",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
