# Generated by Django 5.2 on 2026-04-25 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("societe", "0004_tempspasse_statut"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilHoraireUtilisateur",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("profil_horaire", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="affectations_utilisateurs", to="societe.profilhoraire", verbose_name="Profil horaire")),
                ("utilisateur", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profil_horaire_societe", to=settings.AUTH_USER_MODEL, verbose_name="Salarié")),
            ],
            options={
                "verbose_name": "Affectation profil horaire salarié",
                "verbose_name_plural": "Affectations profils horaires salariés",
                "db_table": "societe_profil_horaire_utilisateur",
                "ordering": ["utilisateur__nom", "utilisateur__prenom"],
            },
        ),
    ]
