# Generated by Django 5.2 on 2026-04-25 14:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0005_profilhoraireutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilhoraire',
            name='heures_productives_an',
            field=models.DecimalField(decimal_places=2, default=Decimal('1600.00'), help_text='BE : 1 600 h ; chantier : 1 490 h.', max_digits=7, verbose_name='Heures productives / an'),
        ),
        migrations.AddField(
            model_name='profilhoraire',
            name='taux_charges_patronales',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.4200'), help_text='Charges employeur sur brut. Défaut 42 %.', max_digits=6, verbose_name='Taux charges patronales'),
        ),
        migrations.AddField(
            model_name='profilhoraire',
            name='taux_charges_salariales',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2200'), help_text='Part salariale : Net = Brut × (1 − taux). Défaut 22 %.', max_digits=6, verbose_name='Taux charges salariales'),
        ),
        migrations.AddField(
            model_name='profilhoraire',
            name='taux_horaire_ht_calcule',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Taux calculé (moyenne simulations)'),
        ),
        migrations.AddField(
            model_name='profilhoraire',
            name='taux_marge_vente',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), help_text='Taux de marge sur prix de vente. Défaut 15 %.', max_digits=6, verbose_name='Marge de vente cible'),
        ),
        migrations.AddField(
            model_name='profilhoraire',
            name='type_profil',
            field=models.CharField(choices=[('be', "Bureau d'études"), ('chantier', 'Chantier'), ('autre', 'Autre')], default='be', max_length=10, verbose_name='Type de profil'),
        ),
        migrations.AddField(
            model_name='profilhoraire',
            name='utiliser_calcul',
            field=models.BooleanField(default=False, help_text='Si activé, taux_horaire_ht est mis à jour automatiquement depuis la moyenne des simulations.', verbose_name='Piloter par les simulations'),
        ),
        migrations.CreateModel(
            name='SimulationSalaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='Ex : Hypothèse basse, Salarié actuel, Recrutement prévu…', max_length=150, verbose_name='Libellé de la simulation')),
                ('salaire_net_mensuel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire net mensuel (€)')),
                ('primes_mensuelles', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Primes mensuelles (€)')),
                ('avantages_mensuels', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Avantages en nature mensuels (€)')),
                ('salaire_brut_estime', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('charges_salariales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('charges_patronales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('cout_employeur_mensuel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('cout_annuel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('dhmo', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='DHMO (€/h coût)')),
                ('taux_vente_horaire', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='Taux de vente horaire (€/h)')),
                ('actif', models.BooleanField(default=True, verbose_name='Inclus dans la moyenne')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='societe.profilhoraire', verbose_name='Profil horaire')),
            ],
            options={
                'verbose_name': 'Simulation salariale',
                'verbose_name_plural': 'Simulations salariales',
                'db_table': 'societe_simulation_salaire',
                'ordering': ['profil', 'ordre', 'date_creation'],
            },
        ),
    ]
