# Generated by Django 5.2 on 2026-04-25 16:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0006_simulation_salaire_profil_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilhoraire',
            name='heures_productives_an',
            field=models.DecimalField(decimal_places=2, default=Decimal('1600.00'), help_text='Heures vendables après congés, administratif et formation. Défaut 1 600 h/an.', max_digits=7, verbose_name='Heures productives / an'),
        ),
        migrations.AlterField(
            model_name='profilhoraire',
            name='type_profil',
            field=models.CharField(choices=[('be', "Bureau d'études"), ('autre', 'Autre')], default='be', max_length=10, verbose_name='Type de profil'),
        ),
    ]
