# Generated by Django 5.2 on 2026-04-25 16:53

import uuid
from decimal import Decimal
from django.db import migrations, models


def initialiser_parametres_societe(apps, schema_editor):
    ParametreSociete = apps.get_model("societe", "ParametreSociete")
    ChargeFixeStructure = apps.get_model("societe", "ChargeFixeStructure")

    ParametreSociete.objects.get_or_create(
        annee=2026,
        defaults={
            "zone_smic": "Mayotte",
            "smic_horaire_brut": Decimal("9.33"),
            "pmss": Decimal("4005.00"),
            "pass_annuel": Decimal("48060.00"),
            "taux_charges_salariales": Decimal("0.2200"),
            "taux_charges_patronales": Decimal("0.4200"),
            "heures_productives_be": Decimal("1600.00"),
            "objectif_marge_nette": Decimal("0.1500"),
            "taux_tva_defaut": Decimal("0.200"),
        },
    )

    charges = [
        ("Loyer / domiciliation / coworking", Decimal("850.00")),
        ("Logiciels CAO/BIM/Office/Cloud", Decimal("1200.00")),
        ("Assurance RC Pro / décennale selon activité", Decimal("650.00")),
        ("Matériel informatique et amortissements", Decimal("500.00")),
        ("Téléphone / internet / énergie", Decimal("300.00")),
        ("Comptabilité / juridique", Decimal("450.00")),
        ("Véhicule / déplacements BE", Decimal("900.00")),
        ("Commercial / communication", Decimal("700.00")),
        ("Formation / veille technique", Decimal("350.00")),
    ]
    for ordre, (libelle, montant) in enumerate(charges, start=1):
        ChargeFixeStructure.objects.get_or_create(
            libelle=libelle,
            defaults={"montant_mensuel": montant, "ordre": ordre, "actif": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0007_alter_profilhoraire_heures_productives_an_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeFixeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=200)),
                ('montant_mensuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'societe_charge_fixe_structure',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='ParametreSociete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.PositiveSmallIntegerField(default=2026, unique=True)),
                ('zone_smic', models.CharField(default='Mayotte', max_length=80)),
                ('smic_horaire_brut', models.DecimalField(decimal_places=2, default=Decimal('9.33'), max_digits=8)),
                ('pmss', models.DecimalField(decimal_places=2, default=Decimal('4005.00'), max_digits=10)),
                ('pass_annuel', models.DecimalField(decimal_places=2, default=Decimal('48060.00'), max_digits=12)),
                ('taux_charges_salariales', models.DecimalField(decimal_places=4, default=Decimal('0.2200'), max_digits=6)),
                ('taux_charges_patronales', models.DecimalField(decimal_places=4, default=Decimal('0.4200'), max_digits=6)),
                ('heures_productives_be', models.DecimalField(decimal_places=2, default=Decimal('1600.00'), max_digits=7)),
                ('objectif_marge_nette', models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=6)),
                ('taux_tva_defaut', models.DecimalField(decimal_places=3, default=Decimal('0.200'), max_digits=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'societe_parametre',
                'ordering': ['-annee'],
            },
        ),
        migrations.RunPython(initialiser_parametres_societe, migrations.RunPython.noop),
    ]
