# Generated by Django 5.2 on 2026-04-25 17:38

from django.db import migrations, models


DECOMPOSITION_DEFAUT = {
    "heures_theoriques_annuelles": 1820,
    "conges_payes": 175,
    "jours_feries_et_absences": 35,
    "administratif_interne": 10,
    "formation_veille": 0,
    "commercial_non_facturable": 0,
}


def initialiser_decomposition(apps, schema_editor):
    ParametreSociete = apps.get_model("societe", "ParametreSociete")
    for parametre in ParametreSociete.objects.all():
        if not parametre.decomposition_heures_productives:
            parametre.decomposition_heures_productives = DECOMPOSITION_DEFAUT
            parametre.heures_productives_be = 1600
            parametre.save(update_fields=["decomposition_heures_productives", "heures_productives_be"])


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0008_chargefixestructure_parametresociete'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresociete',
            name='decomposition_heures_productives',
            field=models.JSONField(blank=True, default=dict, verbose_name='Décomposition heures productives BE'),
        ),
        migrations.RunPython(initialiser_decomposition, migrations.RunPython.noop),
    ]
