# Generated by Django 5.2 on 2026-05-01 18:05

from decimal import Decimal
from django.db import migrations, models


def initialiser_donnees_economiques(apps, schema_editor):
    ParametreSociete = apps.get_model('societe', 'ParametreSociete')
    LigneDevis = apps.get_model('societe', 'LigneDevis')
    SimulationSalaire = apps.get_model('societe', 'SimulationSalaire')
    ProfilHoraire = apps.get_model('societe', 'ProfilHoraire')
    TempsPasse = apps.get_model('societe', 'TempsPasse')

    for parametre in ParametreSociete.objects.all():
        parametre.taux_marge_cible = parametre.objectif_marge_nette
        parametre.save(update_fields=['taux_marge_cible'])

    modes = {
        'horaire': 'taux_profil',
        'forfait': 'forfait_mission',
        'frais': 'frais',
        'sous_traitance': 'sous_traitance',
    }
    for ligne in LigneDevis.objects.all():
        ligne.mode_chiffrage = modes.get(ligne.type_ligne, 'forfait_mission')
        if ligne.type_ligne == 'horaire' and ligne.nb_heures and ligne.taux_horaire:
            ligne.cout_direct_total_estime = Decimal('0.00')
            ligne.marge_estimee_ht = ligne.montant_ht
            ligne.taux_marge_estime = Decimal('1.0000') if ligne.montant_ht else Decimal('0.0000')
        ligne.save(update_fields=['mode_chiffrage', 'cout_direct_total_estime', 'marge_estimee_ht', 'taux_marge_estime'])

    for simulation in SimulationSalaire.objects.all():
        simulation.cout_direct_horaire = simulation.dhmo
        simulation.taux_vente_horaire_calcule_k = simulation.taux_vente_horaire
        simulation.forfait_jour_ht_calcule = (simulation.taux_vente_horaire * Decimal('7.00')).quantize(Decimal('0.01'))
        simulation.save(update_fields=['cout_direct_horaire', 'taux_vente_horaire_calcule_k', 'forfait_jour_ht_calcule'])

    for profil in ProfilHoraire.objects.all():
        profil.taux_vente_horaire_calcule = profil.taux_horaire_ht_calcule or profil.taux_horaire_ht
        profil.forfait_jour_ht_calcule = (profil.taux_vente_horaire_calcule * Decimal('7.00')).quantize(Decimal('0.01'))
        profil.save(update_fields=['taux_vente_horaire_calcule', 'forfait_jour_ht_calcule'])

    for temps in TempsPasse.objects.all():
        temps.cout_direct_horaire = temps.taux_horaire
        temps.taux_vente_horaire = temps.taux_horaire
        temps.montant_vendu_associe = temps.cout_total
        temps.save(update_fields=['cout_direct_horaire', 'taux_vente_horaire', 'montant_vendu_associe'])


class Migration(migrations.Migration):

    dependencies = [
        ('societe', '0009_parametresociete_decomposition_heures_productives'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargefixestructure',
            name='categorie',
            field=models.CharField(choices=[('loyer', 'Loyer'), ('logiciels', 'Logiciels'), ('assurances', 'Assurances'), ('comptabilite', 'Comptabilité'), ('vehicule', 'Véhicule'), ('telephonie', 'Téléphonie'), ('materiel', 'Matériel'), ('documentation', 'Documentation'), ('frais_bancaires', 'Frais bancaires'), ('sous_traitance_structurelle', 'Sous-traitance structurelle'), ('commercial', 'Commercial'), ('autres', 'Autres')], default='autres', max_length=40),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='coefficient_k_applique',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Coefficient K appliqué'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='cout_direct_horaire_reference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Coût direct horaire de référence'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='cout_direct_total_estime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Coût direct total estimé'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='forfait_jour_ht_reference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Forfait jour HT de référence'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='marge_estimee_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Marge estimée HT'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='mode_chiffrage',
            field=models.CharField(blank=True, choices=[('taux_moyen_be', 'Taux horaire moyen BE'), ('taux_profil', 'Taux horaire profil'), ('forfait_jour_profil', 'Forfait jour profil'), ('forfait_mission', 'Forfait mission'), ('frais', 'Frais / débours'), ('sous_traitance', 'Sous-traitance')], default='', max_length=30, verbose_name='Mode de chiffrage'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='nb_jours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Nombre de jours'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='source_tarif',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Source tarif'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='taux_marge_estime',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Taux de marge estimé'),
        ),
        migrations.AddField(
            model_name='parametresociete',
            name='heures_facturables_jour',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='parametresociete',
            name='mode_arrondi_tarif',
            field=models.CharField(choices=[('aucun', 'Aucun'), ('euro', 'Euro'), ('cinq_euros', '5 euros'), ('dix_euros', '10 euros')], default='aucun', max_length=20),
        ),
        migrations.AddField(
            model_name='parametresociete',
            name='pas_arrondi_tarif',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='parametresociete',
            name='strategie_tarifaire',
            field=models.CharField(choices=[('taux_unique', 'Taux moyen unique'), ('taux_par_profil', 'Taux par profil'), ('mixte', 'Mixte')], default='mixte', max_length=20),
        ),
        migrations.AddField(
            model_name='parametresociete',
            name='taux_frais_commerciaux',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='parametresociete',
            name='taux_frais_generaux',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='parametresociete',
            name='taux_imponderables',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='parametresociete',
            name='taux_marge_cible',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1500'), max_digits=6),
        ),
        migrations.AddField(
            model_name='parametresociete',
            name='taux_risque_alea',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='profilhoraire',
            name='coefficient_k_applique',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=8, verbose_name='Coefficient K appliqué'),
        ),
        migrations.AddField(
            model_name='profilhoraire',
            name='cout_direct_horaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Coût direct horaire'),
        ),
        migrations.AddField(
            model_name='profilhoraire',
            name='forfait_jour_ht_calcule',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Forfait jour HT calculé'),
        ),
        migrations.AddField(
            model_name='profilhoraire',
            name='inclure_taux_moyen',
            field=models.BooleanField(default=True, verbose_name='Inclus dans le taux moyen pondéré'),
        ),
        migrations.AddField(
            model_name='profilhoraire',
            name='poids_ponderation',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, verbose_name='Poids de pondération'),
        ),
        migrations.AddField(
            model_name='profilhoraire',
            name='taux_vente_horaire_calcule',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Taux de vente horaire calculé'),
        ),
        migrations.AddField(
            model_name='simulationsalaire',
            name='cout_direct_horaire',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='Coût direct horaire'),
        ),
        migrations.AddField(
            model_name='simulationsalaire',
            name='forfait_jour_ht_calcule',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Forfait jour HT calculé'),
        ),
        migrations.AddField(
            model_name='simulationsalaire',
            name='taux_vente_horaire_calcule_k',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='Taux de vente horaire via coefficient K'),
        ),
        migrations.AddField(
            model_name='tempspasse',
            name='cout_direct_horaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Coût direct horaire'),
        ),
        migrations.AddField(
            model_name='tempspasse',
            name='marge_estimee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Marge estimée'),
        ),
        migrations.AddField(
            model_name='tempspasse',
            name='montant_vendu_associe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Montant vendu associé'),
        ),
        migrations.AddField(
            model_name='tempspasse',
            name='taux_vente_horaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Taux de vente horaire'),
        ),
        migrations.RunPython(initialiser_donnees_economiques, migrations.RunPython.noop),
    ]
