# Generated by Django 5.2 on 2026-05-02 17:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_dossierdocumentprojet_document_dossier_and_more'),
        ('organisations', '0001_initial'),
        ('projets', '0013_livrableprojet'),
        ('societe', '0011_tempspasse_categorie_temps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelanceAutomatique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('devis_en_attente', 'Devis en attente'), ('facture_impayee', 'Facture impayée'), ('facture_retard', 'Facture en retard'), ('paiement_echoue', 'Paiement échoué')], max_length=30)),
                ('cible_type', models.CharField(max_length=60)),
                ('cible_id', models.CharField(max_length=80)),
                ('niveau', models.CharField(choices=[('relance_1', 'Relance 1'), ('relance_2', 'Relance 2'), ('relance_3', 'Relance 3'), ('mise_en_demeure', 'Mise en demeure')], default='relance_1', max_length=30)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('envoyee', 'Envoyée'), ('echouee', 'Échouée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('date_prevue', models.DateTimeField()),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('email_destinataire', models.EmailField(blank=True, max_length=254)),
                ('objet', models.CharField(blank=True, max_length=250)),
                ('corps', models.TextField(blank=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='societe/relances/%Y/%m/')),
                ('historique', models.JSONField(blank=True, default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'societe_relance_automatique',
                'ordering': ['date_prevue'],
            },
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='case_conditions_acceptees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='date_consultation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='email_signataire',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='fonction_signataire',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='historique_commercial',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='ip_acceptation',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='lien_public_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='lien_public_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='motif_refus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='nom_signataire',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='signature_electronique_simple',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='user_agent_acceptation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='bic_destination',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='facture',
            name='chorus_derniere_synchro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='chorus_flux_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='facture',
            name='chorus_numero_depot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='facture',
            name='chorus_statut',
            field=models.CharField(blank=True, default='a_deposer', max_length=40),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_derniere_relance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='historique_commercial',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facture',
            name='iban_destination',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='facture',
            name='interets_moratoires_appliques',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='lien_paiement',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='livrables_liberables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(choices=[('virement', 'Virement'), ('carte', 'Carte bancaire'), ('chorus_pro', 'Chorus Pro'), ('mixte', 'Mixte')], default='virement', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_interets_moratoires',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='nombre_relances',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facture',
            name='reference_virement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('acompte', 'Acompte'), ('situation', "Situation d'avancement"), ('solde', 'Solde'), ('avoir', 'Avoir'), ('proforma', 'Proforma')], default='situation', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_initiation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='devise',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='paiement',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paiement',
            name='prestataire',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('payplug', 'PayPlug'), ('payline', 'Payline'), ('banque', 'Banque'), ('chorus_pro', 'Chorus Pro'), ('manuel', 'Manuel')], default='manuel', max_length=30),
        ),
        migrations.AddField(
            model_name='paiement',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_societe', to='projets.projet'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='rapprochement_bancaire',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_banque',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_transaction',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('initie', 'Initié'), ('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('echoue', 'Échoué'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], default='confirme', max_length=20),
        ),
        migrations.AlterField(
            model_name='devishonoraires',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('pret', 'Prêt'), ('envoye', 'Envoyé'), ('consulte', 'Consulté'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré'), ('annule', 'Annulé'), ('remplace', 'Remplacé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('envoyee', 'Envoyée'), ('deposee_chorus', 'Déposée Chorus Pro'), ('en_attente_paiement', 'En attente de paiement'), ('en_retard', 'En retard'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('relancee', 'Relancée'), ('contentieux', 'Contentieux'), ('annulee', 'Annulée'), ('avoir', 'Avoir'), ('proforma', 'Proforma')], default='brouillon', max_length=25),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('chorus_pro', 'Chorus Pro'), ('manuel', 'Manuel'), ('prelevement', 'Prélèvement automatique'), ('autre', 'Autre')], default='virement', max_length=20),
        ),
        migrations.CreateModel(
            name='AffaireCommerciale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='Référence affaire')),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé')),
                ('contact_client', models.CharField(blank=True, max_length=200, verbose_name='Contact client')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email contact')),
                ('type_client', models.CharField(blank=True, max_length=60, verbose_name='Type client')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('devis_a_preparer', 'Devis à préparer'), ('devis_envoye', 'Devis envoyé'), ('devis_accepte', 'Devis accepté'), ('devis_refuse', 'Devis refusé'), ('affaire_validee', 'Affaire validée'), ('affaire_perdue', 'Affaire perdue'), ('projet_cree', 'Projet créé'), ('archivee', 'Archivée')], default='brouillon', max_length=30)),
                ('origine', models.CharField(choices=[('manuel', 'Manuel'), ('formulaire', 'Formulaire'), ('import', 'Import'), ('recommandation', 'Recommandation'), ('autre', 'Autre')], default='manuel', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('montant_estime_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('montant_estime_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('cadre_juridique', models.CharField(choices=[('marche_public', 'Marché public'), ('marche_prive', 'Marché privé'), ('mixte', 'Mixte'), ('hors_marche', 'Hors marché / conseil')], default='marche_prive', max_length=30)),
                ('mode_commande', models.CharField(choices=[('consultation_directe', 'Consultation directe'), ('appel_offres', "Appel d'offres"), ('accord_cadre', 'Accord-cadre'), ('marche_subsequent', 'Marché subséquent'), ('amo', 'AMO / conseil'), ('sous_traitance', 'Sous-traitance'), ('cotraitance', 'Co-traitance'), ('audit', 'Audit / expertise')], default='consultation_directe', max_length=30)),
                ('mode_facturation', models.CharField(choices=[('forfait', 'Forfait'), ('temps_passe', 'Temps passé'), ('echeancier', 'Échéancier'), ('avancement', 'Avancement'), ('mixte', 'Mixte')], default='forfait', max_length=30)),
                ('mode_paiement_prevu', models.CharField(choices=[('virement', 'Virement'), ('carte', 'Carte bancaire'), ('chorus_pro', 'Chorus Pro'), ('mixte', 'Mixte')], default='virement', max_length=30)),
                ('delai_validite_devis_jours', models.PositiveSmallIntegerField(default=30)),
                ('date_derniere_relance', models.DateTimeField(blank=True, null=True)),
                ('date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('date_refus', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('validation_manuelle_admin', models.BooleanField(default=False)),
                ('validation_manuelle_date', models.DateTimeField(blank=True, null=True)),
                ('validation_manuelle_motif', models.TextField(blank=True)),
                ('donnees_metier', models.JSONField(blank=True, default=dict)),
                ('historique', models.JSONField(blank=True, default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires_commerciales', to='organisations.organisation', verbose_name='Client')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires_creees', to=settings.AUTH_USER_MODEL)),
                ('devis_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires_principales', to='societe.devishonoraires')),
                ('projet_lie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaire_commerciale', to='projets.projet')),
                ('validation_manuelle_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affaires_validees_manuellement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affaire commerciale',
                'verbose_name_plural': 'Affaires commerciales',
                'db_table': 'societe_affaire_commerciale',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.AddField(
            model_name='devishonoraires',
            name='affaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='societe.affairecommerciale', verbose_name='Affaire commerciale'),
        ),
        migrations.AddField(
            model_name='facture',
            name='affaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='societe.affairecommerciale', verbose_name='Affaire commerciale'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='affaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='societe.affairecommerciale'),
        ),
        migrations.CreateModel(
            name='LivraisonLivrable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('livrable_code', models.CharField(blank=True, max_length=120)),
                ('statut', models.CharField(choices=[('bloque', 'Bloqué'), ('disponible', 'Disponible'), ('envoye', 'Envoyé'), ('telecharge', 'Téléchargé'), ('expire', 'Expiré')], default='bloque', max_length=20)),
                ('condition_livraison', models.CharField(choices=[('paiement_recu', 'Paiement reçu'), ('facture_deposee_chorus', 'Facture déposée Chorus Pro'), ('validation_admin', 'Validation admin'), ('gratuit', 'Gratuit')], default='paiement_recu', max_length=30)),
                ('lien_token_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_premier_telechargement', models.DateTimeField(blank=True, null=True)),
                ('nombre_telechargements', models.PositiveIntegerField(default=0)),
                ('email_destinataire', models.EmailField(blank=True, max_length=254)),
                ('validation_admin_motif', models.TextField(blank=True)),
                ('historique', models.JSONField(blank=True, default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='societe.affairecommerciale')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_commerciales', to='documents.document')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='societe.facture')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_commerciales', to='projets.projet')),
            ],
            options={
                'db_table': 'societe_livraison_livrable',
                'ordering': ['-date_creation'],
            },
        ),
    ]
